### PR TITLE
Adding descriptions to all VIs

### PR DESCRIPTION
**Pull request by oscarfonloz**
# :warning: THIS PR CHANGES ALL VIS IN THE SCRIPTING LIBRARY. MERGE AT THE END.
# [PR 145](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/pull/145) and [PR 146](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/pull/146) must be merged first into main.

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

1. Adding VI descriptions to all VIs and CTL files in the scripting API
2. Adding a tool that allows us to load all these descriptions from a CSV because it's easier to check spelling and work with our tech writer this way.

### Why should this Pull Request be merged?

We require of documentation in the VIs to ship a properly built API.

### What testing has been done?

No functional changes were made to the VIs. All unit tests pass.

### CODE REVIEW

**Comment by rtzoeller** [comment]
Providing feedback on the tool itself now, as even though the other VIs conflict, the tool can be reviewed independently.

- [ ] Error 7, which occurs if the library path is invalid, seems like it should also be listed as a recoverable error.
- [ ] ~~Why is the 5xxx range listed as recoverable?~~ Ahh, I see that you're using it for your own errors throughout the application. Probably worth mentioning in `Error Handler.vi`, like with Error 43.
- [ ] `Import from CSV.vi`'s icon claims it is `Export to CSV.vi`.
- [ ] I'm not understanding the usage of "This VI" as the default value in `Save Documentation to VIs.vi`.
- [ ] I don't believe you need to read/specify the VI path in `Save Documentation to VIs.vi`. Leaving the path unspecified should save it in place.
- [ ] Clicking Load Library should unload any loaded VIs first. I loaded a few different libraries and observed that all previously loaded VIs stayed in memory, despite not appearing in the list of VIs.

I'm glad you aren't saving VIs which already match the description!

**Comment by oscarfonloz** [comment]
> Providing feedback on the tool itself now, as even though the other VIs conflict, the tool can be reviewed independently.
> 
> * [x]  Error 7, which occurs if the library path is invalid, seems like it should also be listed as a recoverable error.
> * [x]  ~Why is the 5xxx range listed as recoverable?~ Ahh, I see that you're using it for your own errors throughout the application. Probably worth mentioning in `Error Handler.vi`, like with Error 43.
> * [x]  `Import from CSV.vi`'s icon claims it is `Export to CSV.vi`.
> * [x]  I'm not understanding the usage of "This VI" as the default value in `Save Documentation to VIs.vi`.
> * [x]  I don't believe you need to read/specify the VI path in `Save Documentation to VIs.vi`. Leaving the path unspecified should save it in place.
> * [x]  Clicking Load Library should unload any loaded VIs first. I loaded a few different libraries and observed that all previously loaded VIs stayed in memory, despite not appearing in the list of VIs.
> 
> I'm glad you aren't saving VIs which already match the description!

Yay! Thanks for this feedback. I incorporated everything.

**Comment by rtzoeller** [comment]
@oscarfonloz would it be possible to split this change into two PRs, one that adds the tool to apply descriptions, and a second (possibly to be put up for review later) that applies the descriptions?

That would allow us to finish reviewing the tool (and submit that PR now) in isolation from touching every VI and reviewing the individual descriptions.

**Comment by oscarfonloz** [comment]
> @oscarfonloz would it be possible to split this change into two PRs, one that adds the tool to apply descriptions, and a second (possibly to be put up for review later) that applies the descriptions?
> 
> That would allow us to finish reviewing the tool (and submit that PR now) in isolation from touching every VI and reviewing the individual descriptions.

Yep! Separated to [PR 148](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/pull/148)

**Comment by rtzoeller** [comment]
@oscarfonloz I think this PR is ready (in terms of other PRs going in); it probably makes sense to just re-branch from `ni/main` so you have a clean history and no other changes are accidentally pulled in.

**Comment by oscarfonloz** [comment]
> @oscarfonloz I think this PR is ready (in terms of other PRs going in); it probably makes sense to just re-branch from `ni/main` so you have a clean history and no other changes are accidentally pulled in.

I agree, I'm going to abandon this PR and branch again from main.

**Comment by oscarfonloz** [comment]
Opened [PR 150](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/pull/150)

**Pull request closed without merging**
