### PR TITLE
Mass compile custom device to 2017

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Mass compile custom device to 2017

### Why should this Pull Request be merged?

The modules libraries are maintained in 2017, and it is difficult to develop for the custom device in an earlier version. This should improve developer efficiency when making future changes.

### What testing has been done?

Confirmed I can build the custom device after the mass compile.

### CODE REVIEW

**Comment by rtzoeller** [comment]
I will manually update and resolve conflicts for https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/pull/14 after this change is submitted.

**Comment by buckd** [comment]
> Remove pre-built Modules zip files

Thank you!

**Comment by csjall** [comment]
I get an error when loading the project looking for Modules.lvlibp. 

image

**Comment by buckd** [comment]
> I get an error when loading the project looking for Modules.lvlibp.

Someone hasn't built the custom device from the ground up in a while...
The Modules library needs to be built from [this repo](https://github.com/ni/niveristand-scan-engine-module-libraries) in the version of LV you're building the custom device for. Then you have to copy that library to the `Custom Device Source` directory for the target OS you want.

**Pull request merged**
