### PR TITLE
Add Scripting for 9375

### PR DESCRIPTION
**Pull request by oscarfonloz**
# :warning: [PR 139](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/pull/139) must be merged first into main.

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This PR contains the scripting for the DIO module 9375

### Why should this Pull Request be merged?

This PR contains the scripting for the DIO module 9375

#### Implementation Details

I refactored the digital inputs and outputs code to make more efficient the reading process. Since both DI and DO modes use the same pattern to read back the channels information, then I created a new Digital mode parent class for both of these to contain this method and avoid code duplication.

This PR contains the following assumptions and implementation details:
1. The DI, DO and DIO channels will always use the Digital Channel class for their channels
1. The DIO modules will always be half DI and half DO. If this is not the case, we need to figure out a way to declare how much DI and DO channels each mode has
1. The DIO mode uses both the DI and DO (i.e. DIO is composed by its siblings) because it uses them to create each channel type without having to implement this mechanism itself

### What testing has been done?

Added its unit test and ensured the rest of the unit tests still pass

### CODE REVIEW

**Comment by oscarfonloz** [comment]
@rdecarreau I would appreciate a peer review if you have a chance, before ASW comes back from the holiday 😊

**Comment by rtzoeller** [comment]
@oscarfonloz I'm fine with the change to consolidate to a DIO class, but I'd like @buckd's opinion as well.

There's a number of VIs which are reporting no changes, but I think it's possible they have changed subtly due to the class hierarchy changing. I'd rather submit them as is then risk fighting LabVIEW about corrupted class constants down the road.

I do think we need to prioritize allowing setting the mode for individual channels (or groups of channels) within a slot, and doing so before the initial release so we don't find ourselves needing to break compatibility as we adjust connector panes. I imagine this will be very similar to how different counter modes are specified for specialty digital modules.

image

**Review by rtzoeller — APPROVED** [review]

**Comment by oscarfonloz** [comment]
I agree with your comment @rtzoeller. I wasn't very happy with the channel count assumption I documented in the comment you show, either. I am happy to keep exploring other options if we think the supportability of the API will be impacted. We can do this in this PR or in a new work item for this iteration... I don't want to hold back Deborah's palettes or the Poly VIs, either.
(so much to do, too many people, and so little time! hahaha)

**Comment by rtzoeller** [comment]
@oscarfonloz we should definitely defer it out of this PR, to keep other work unblocked. It's probably worth creating a new work item to track this explicitly.

**Comment by buckd** [comment]
I'm fine with creating the common base class for DIO.

Also, I've been mentioning it in our discussions for some time, but I agree with @rtzoeller that we should have an implementation for mixed modes in a module slot before we release. That change should not be included in this PR, but we should absolutely have a work item for tracking.

**Review by buckd — APPROVED** [review]

**Pull request merged**
