### PR TITLE
Bump version to 4.5

### PR DESCRIPTION
**Pull request by csjall**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

We are adding support for new hardware in the RSI Module repository. This breaks compatibility with existing system definition files. Mutate existing system definition files by rewriting the module model enum.

### Why should this Pull Request be merged?

Customers will not be able to load existing system definition files without this change.

### What testing has been done?

Load existing system definition file prior to version 4.5 and confirm properties are deserialized correctly.

### CODE REVIEW

**Comment by rtzoeller** [comment]
I will trigger a build and review once I can test the changes.

**Comment by rtzoeller** [comment]
The tests for Specialty Digital are failing with these changes (tested in 2017, did not test the others). Curiously, if I open and save the test files such that the mutation changes are made the tests then pass. This would appear to point to the mutation not running (properly or at all?) when deployed directly through the API.

The code changes look good (aside from the test failures).

**Comment by csjall** [comment]
> The tests for Specialty Digital are failing with these changes (tested in 2017, did not test the others). Curiously, if I open and save the test files such that the mutation changes are made the tests then pass. This would appear to point to the mutation not running (properly or at all?) when deployed directly through the API.
> 
> The code changes look good (aside from the test failures).

I will look into the mutation code and see why it is not running for the tests.

**Comment by buckd** [comment]
The On Load action doesn't run during deployment (and I don't feel it should). Since the mutation is called in the On Load code and the tests only deploy existing sysdefs, no mutation will happen.

**Comment by rtzoeller** [comment]
This problem is likely affecting other custom devices that do mutation. Once we have found a solution here, we should apply it to the other custom devices (e.g. the Engine Simulation Toolkit custom device).

**Comment by csjall** [comment]
OnLoad means "when the configuration front panel is loaded" not "when the system definition is loaded". Since we don't load the front panel for the custom device in the automated test we never mutate the system definition. We could try to manually invoke the "On Load" action as part of the deployment in the automated testing tools.

**Pull request merged**
