### PR TITLE
Adding support for NI 9225 Scripting API

### PR DESCRIPTION
**Pull request by Sarci1**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Fixed a bug in Get/Set Units to address the correct data member.
- Created AI channel, AI Vrms channel, AI mode, and AI Vrms mode and subsequent utilities to support creation of 9225.
- Added 9225 class and unit tests and unique get/set slot unit test to check that the class stays the same.
- Updated Get/Set slot to include new modes.
- Changed Convert Module Model to Module Class.vi to include 9225

### Why should this Pull Request be merged?

Add support for 9225 and future AI modules.

### What testing has been done?

Added unit tests for the 9225 including a specific get/set slot unit test to verify the class input is the same as the one that is returned.

### CODE REVIEW

**Review by buckd — APPROVED** [review]
This all looks good to me.

The one thing that was hard for me to digest was why there were changes to the `NI 947x Test` classes. Changing some overrides to no longer be required was a subtle change, but I had to look at the changes 3 times to find it.

I'm ok with leaving both the DO- and AI-specific VIs in `Module Test.lvclass` for this change, but as we add more modules and tests, it may make more sense to subclass `Module Test.lvclass` for the specific module types so seemingly unrelated changes won't muddy diffs.

I'll wait on @rtzoeller to take a look, since he's more familiar with the existing code and let him comment on whether he wants to change the class hierarchy for the tests.

**Comment by rtzoeller** [comment]
I agree with @buckd about looking for a better architecture for `Module Test.lvclass`, but am also okay with deferring that out of this PR - the current code seems to work and I can live with the implementation, but as we add more module types I think we'll want to revisit this.

Attempting to test every mode and expecting most to no-op is bit tricky to follow. 
image

---

@Sarci1 I really only have minor nitpicks about the code. I'll give you the opportunity to address whatever you think is worth it before merging, but don't feel obligated to fix everything - this is more of a stream of consciousness than a well-groomed list of feedback.

Let me know when you're happy with things and I'll merge this pull request.

- [ ] Should `AI Channel.lvclass:Define Default Prefix.vi` be private?

- [ ] The case structure labels are overlapping in `Get Slot.vi`. 
image
image

- [ ] We can remove the need to clear a specific error in `Get Slot.vi` by changing up the error handling. This code was already present, but I'm calling it out here because we are going to keep modifying this VI. I.e. something like
image

- [ ] It seems like we're going to want the "is analog" check to be wholly separate from the "is input" check in `Get Slot.vi`, since we know we will be adding AO and DIO. This could just be done when adding these modes though. I.e. use multiple case structures instead of ANDing the checks.
image

- [ ] There's no need to re-store the target ref in `test_Set and Get 9225.vi` since it's a reference type. We're doing this in the other tests in the same class, but no need to fix them in this PR.
image

**Review by rtzoeller — APPROVED** [review]

**Comment by debryant** [comment]
> I agree with @buckd about looking for a better architecture for Module Test.lvclass, but am also okay with deferring that out of this PR - the current code seems to work and I can live with the implementation, but as we add more module types I think we'll want to revisit this.  Attempting to test every mode and expecting most to no-op is bit tricky to follow.

Oscar, Lynn and I had some discussion around this last week too. We created AzDO Task 1173472 "Consider making the top level module test smarter" to revisit this later.

**Comment by debryant** [comment]
Lynn doesn't currently have access to GitHub. Something about the changes to the GitHub Enterprise license. :( She is looking into it. In the meantime she says :
"I'm ok addressing his feedback in a later PR since we'll need to modify those VIs again with other modes we add".

So.... if ya'll are ok with this, can we get this PR merged into the code base?

**Comment by rtzoeller** [comment]
@debryant we're also seeing issues. Thanks for the heads up.

**Comment by buckd** [comment]
I sent the Github admins an email and they reverted the change. I have access to the NI github again, so Lynn should try again.


Sláinte,
Donovan

________________________________

**Pull request merged**
