### PR TITLE
Added an example to read back a module's configuration

### PR DESCRIPTION
**Pull request by oscarfonloz**
## ℹ️ This PR branches from NI\main

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Add examples showing how to read back known and unknown module types.

### Why should this Pull Request be merged?

This example is a requirement from the feature specification for the scan engine custom device scripting.

### What testing has been done?

Manual testing. Should we create unit tests for the examples to ensure these run without errors?

### CODE REVIEW

**Comment by rtzoeller** [comment]
The example itself looks fine, but the examples build is failing locally for me (and on the build machine). Not sure why.

**Comment by Karl-G1** [comment]
@rtzoeller I did some quick digging on this, and it looks like the VIs/project are currently linking against scripting calls that are not in this branch's build (or perhaps legacy).
image

Making sure the repo is clean at that branch, building everything fresh, then forcing a recompile on the VIs seems to get rid of those dependencies, and the VIs executes successfully. However, the build still fails as those missing dependencies show back up when attempting to build.

Selecting two additional exclusions allows the build to succeed, but I'm not sure if that is a valid workaround.
image

**Comment by rtzoeller** [comment]
@Karl-G1 I did a clean build locally, including clearing out vi.lib and the LabVIEW object cache and I'm still seeing this issue. 

@oscarfonloz are you able to build the examples with your change?

**Comment by rtzoeller** [comment]
> Selecting two additional exclusions allows the build to succeed, but I'm not sure if that is a valid workaround.

My litmus test of "what does R+F do?" says that we should not need to select those exclusions.

**Comment by rtzoeller** [comment]
Doing some more digging, it appears that the post-build action is failing with the nondescript error. I will investigate.

**Comment by oscarfonloz** [comment]
Thanks @rtzoeller. I did the following experiment and got weird results:
1. Checkout the branch
2. Merge with what we currently have in main
3. Build the scripting distribution
4. Replace the output in vi.lib, per required by the examples
5. Open the example

I see an error telling me the classes are broken because of the owning library:
image

I am unsure of why at this point :(

**Comment by rtzoeller** [comment]
@Karl-G1 it looks like your solution is the correct one.

The post-build step is failing due to `Modules.lvlibp` not being copied correctly, since it's in vi.lib. This wasn't an issue for R+F, as while it makes use of packed project libraries, they are not use by the scripting examples (they are engine-only). Although there is an existing example, it doesn't script any specific modules, and as such does not pull the packed project library in as a dependency - which is why the build has succeeded up until now.

@oscarfonloz please check the "Exclude dependent **shared** libraries" option in the "Additional Exclusions" section of the build specification. That should fix the issue.

**Comment by rtzoeller** [comment]
@oscarfonloz I am going to wait to investigate fixing the build until @debryant has another in-flight example ready.

**Comment by debryant** [comment]
Note that I opted to create a local example subVI that reads the name and mode rather than add such a VI to the API. Waffled on whether to add it to the Example lvlib or not. I could go either way. The VIs in that library are esp needed in a lvlib so that they aren't cross loaded with the same named VI in other example directories.
The changes to the other VIs are caused by a small change to the icon only.

**Comment by rtzoeller** [comment]
In the documentation `Read Configuration with Known Module.vi`, the slot numbers are incorrect. The slots in the custom device (as with physical cRIOs) are 1-indexed, but the documentation refers to "slot 0" and "slot 1". These should either be "slot 1" and "slot 2", or "first slot" and "second slot".

**Review by rtzoeller — APPROVED** [review]

**Pull request merged**
