### PR TITLE
Add counter pwm input mode

### PR DESCRIPTION
**Pull request by rdecarreau**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds support for Counter PWM input mode.

### Why should this Pull Request be merged?

To create modules which support this mode of input

### What testing has been done?

Ran the vi tests locally, although those don't cover this new mode yet. I modified the 9422 locally to use the new CPI mode and that passed tests.

### CODE REVIEW

**Comment by rtzoeller** [comment]
- [ ] I'm a bit confused by naming. The existing PWM output mode is called `PWM Mode`, and this one is called `Counter PWM Input Mode`. Should the existing class be named `Counter PWM Output Mode`, or am I missing something?

- [ ] The nested acronyms in `CPI` bug me a bit; I would not immediately assume that `CPI` was related to PWM, and it looks like it would conflict with the acronym for period measurements on specialty digital modules. I'm wondering if there's a clearer short-hand we can use.

- [ ] In `Convert CPI Module to Slot Configuration.vi`, I'd prefer if we used the ring types rather than numeric literals. Unfortunately they aren't typedef'd, so you need to copy it, but IMO it makes the code much clearer.
image

**Comment by rdecarreau** [comment]
@rtzoeller I named it this way because this is "Counter" mode with "PWM" measurement mode. I don't think we had a convention for this before.

**Comment by rdecarreau** [comment]
@rtzoeller Updated the naming and acronyms, updated to use typedefs (controls copied from the SD Modules class).

**Comment by rtzoeller** [comment]
@rdecarreau it looks like `CPI` is still used in the icon for `Read Counter Input PWM Module.vi`.

**Review by buckd — COMMENTED** [review]
- [ ] In `Get Slot.vi`, arrange the case structure diagrams in numerical order. It's currently Default, 2, 3, 0, 1.
- [ ] `SD Measurement Mode.ctl` and `SD DIO Mode.ctl` need to be added to the scripting library.

**Comment by rdecarreau** [comment]
Removed CPI, good catch
Sorted Get Slot cases (@oscarfonloz take note of this)
Added controls.

**Review by buckd — APPROVED** [review]
Waiting on successful build and @rtzoeller to merge.

**Pull request merged**
