### PR TITLE
Adding Module support for NI 9475 and NI 9474

### PR DESCRIPTION
**Pull request by Sarci1**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This pull request demonstrates how to contain module information in classes by supplying the methods to create and read an NI 9475 and NI 9474 module classes. These classes will be used for data storage. Included in the PR are the necessary classes that make up the module: channels and modes. Channels contain the channel information: units, name, etc. Modes dictate how to configure the module: PWM output, digital output, etc. 

I've added one new error in the event the user attempts to configure a module with a channel count that isn't the expected channel count.

Also included in the PR is a unit test abstraction to allow us to validate the module data storage. 

### Why should this Pull Request be merged?

These classes will be passed into get and set methods that will then script the module data into the system definition.

### What testing has been done?

I've included unit tests that validate the creation of the modules with different modes with random and default parameters. It also tests for the scenario where the creation errors if an incorrect number of channels is passed.

### CODE REVIEW

**Comment by rtzoeller** [comment]
Since this is a large change, I'll provide feedback incrementally to keep you unblocked (so you can fix things as I find them).

- [ ] LabVIEW isn't reporting any diffs for `Custom Device Source/Type Defs/Host - FPGAScanInterfaceMode.ctl`; can this file be reverted?
- [ ] We can remove the per-module boilerplate of overriding `Define Name.vi` if we can assume module classes are always leaf classes. A child class which is not a leaf class could still provide it's own implementation.
image
https://regex101.com/r/HPtm7L/1

**Comment by rtzoeller** [comment]
- [ ] `Mode.lvclass` being an empty class (effectively an empty interface, although LV 2017 lacks the concept) seems like a [code smell](https://hackernoon.com/are-interfaces-code-smell-bd19abc266d3), although I'm not sure the alternatives make sense in LV. The child classes define methods with the same names, although different signatures, and explicit casting to a subclass is required in order to do _anything_ with a `Mode.lvclass` instance. This isn't a request to change anything, but instead to have a further conversation about the design of the `Mode.lvclass` inheritance system.

- [ ] In `Counter Driven Output Mode.lvclass:Create Channel Array.vi` (as well as the same method on other child classes of `Mode.lvclass`), we are allegedly taking in an "array size". Except it isn't the size of the array being passed in - we allow users to pass in an empty array; in this case the "array size" parameter will be non-zero while the array is actually empty. Please rename the "array size" parameter, e.g. to "expected channel count".
image

**Comment by rtzoeller** [comment]
- [ ] Where did the list of frequencies in `PWM Output Channel.lvclass:Frequency.ctl` come from? I am slightly concerned that the possible range of frequencies might differ by hardware (although I'm not certain of this), and that the current design doesn't allow us to add new ones (other than at the end, out of order).

- [ ] What is the expectation for making the factory VIs accessible to the user? Are we placing `Create NI 9474 - Counter Driven Output.vi`, `Create NI 9474 - Digital Output.vi`, and `Create NI 9474 - PWM Output.vi` on a 9474 palette? Should there be a poly-VI for these?

**Comment by rtzoeller** [comment]
- [ ] We should restrict this check to look for specific error codes.
image

**Comment by rtzoeller** [comment]
- [ ] Can you include the regex101 link I provided (or make your own) in the base implementation of `Define Name.vi` as a comment? I find it is helpful for understanding regexes when reading unfamiliar code.

**Comment by Sarci1** [comment]
> * [ ]  `Mode.lvclass` being an empty class (effectively an empty interface, although LV 2017 lacks the concept) seems like a [code smell](https://hackernoon.com/are-interfaces-code-smell-bd19abc266d3), although I'm not sure the alternatives make sense in LV. The child classes define methods with the same names, although different signatures, and explicit casting to a subclass is required in order to do _anything_ with a `Mode.lvclass` instance. This isn't a request to change anything, but instead to have a further conversation about the design of the `Mode.lvclass` inheritance system.

Yes, I'm definitely open to design suggestions. Benji and I thought this would allow us to better co-develop, ideally allowing the developers to just extend classes, rather than modify parents as we go.

- [x]  In `Counter Driven Output Mode.lvclass:Create Channel Array.vi` (as well as the same method on other child classes of `Mode.lvclass`), we are allegedly taking in an "array size". Except it isn't the size of the array being passed in - we allow users to pass in an empty array; in this case the "array size" parameter will be non-zero while the array is actually empty. Please rename the "array size" parameter, e.g. to "expected channel count".
>   image

**Comment by Sarci1** [comment]
> * [x]  We should restrict this check to look for specific error codes.
>   image

I totally missed that input into the VI. Thank you.

**Comment by Sarci1** [comment]
> * [ ]  Where did the list of frequencies in `PWM Output Channel.lvclass:Frequency.ctl` come from? I am slightly concerned that the possible range of frequencies might differ by hardware (although I'm not certain of this), and that the current design doesn't allow us to add new ones (other than at the end, out of order).

This is a valid concern. I haven't done the due diligence here, mostly having recreated what I could see in these two modules. I'll think on how to do this better, but any ideas from your end in the meantime are welcome.

> * [ ]  What is the expectation for making the factory VIs accessible to the user? Are we placing `Create NI 9474 - Counter Driven Output.vi`, `Create NI 9474 - Digital Output.vi`, and `Create NI 9474 - PWM Output.vi` on a 9474 palette? Should there be a poly-VI for these?

Yes, I still plan on having a poly-VI, but not committed on whether or not we'll have a per-module poly-VI only or have it encompass more than a single module. I'm concerned that by having 1 poly-VI per module we'll end up having a huge palette. The other alternative is that we'll have a huge drop-down.

**Comment by rtzoeller** [comment]
> > - [ ]  Where did the list of frequencies in `PWM Output Channel.lvclass:Frequency.ctl` come from? I am slightly concerned that the possible range of frequencies might differ by hardware (although I'm not certain of this), and that the current design doesn't allow us to add new ones (other than at the end, out of order).
>
> This is a valid concern. I haven't done the due diligence here, mostly having recreated what I could see in these two modules. I'll think on how to do this better, but any ideas from your end in the meantime are welcome.

@buckd as our resident DAQ expert, do you know how the list of supported PWM frequencies vary by module?

The future-proof option I see would be to return the frequency either as a raw numeric, or as a ring with the values being equal to the frequencies (i.e. not sequential).

**Review by rtzoeller — APPROVED** [review]
Approving conditional on a decision being made about representing PWM frequencies, and agreement from @niphilj and @buckd on the best design for handling the different modes (which may be the current design).

**Comment by niphilj** [comment]
Good concerns @rtzoeller about the Mode.lvclass, and the frequency Enum. I don't have better suggestions either. @buckd , I'll let you weigh in as well.

**Review by niphilj — APPROVED** [review]

**Comment by buckd** [comment]
> @buckd as our resident DAQ expert, do you know how the list of supported PWM frequencies vary by module?

I tracked down the how those frequencies are set in a LabVIEW project, and all of those frequencies are hard-coded into a single period control. The values in that control are never modified, except on page load when the value is reinitialized to the default. So, I'm not concerned about subsets of those frequencies being unsupported on different modules. We could still populate the frequencies from some other file on disk, but it would be something we create and it would match those frequencies. We can't ask RIO for what they are (that I can tell).

I'm fine with `Mode.lvclass`.

**Review by buckd — APPROVED** [review]

**Pull request merged**
