### PR TITLE
Add capability to get the references to the modules when looking for …

### PR DESCRIPTION
**Pull request by oscarfonloz**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adding the capability to get the references to the slots from the Find Local Chassis function

### Why should this Pull Request be merged?

It is very useful for the scripting API to be able to get all the references to the slots inside a chassis

### What testing has been done?

Added a unit test that ensures this functionality works properly

### CODE REVIEW

**Comment by oscarfonloz** [comment]
@Sarci1 just reminded me that we need to return the slots in order, so this PR is not ready yet. I will add that functionality on Friday because I’m OOO tomorrow Thursday.

**Comment by oscarfonloz** [comment]
> @Sarci1 just reminded me that we need to return the slots in order, so this PR is not ready yet. I will add that functionality on Friday because I’m OOO tomorrow Thursday.

@rtzoeller @buckd I have addressed this concern and the PR should be ready for review :)

**Comment by rtzoeller** [comment]
There is still an asymmetry between `Add Local Chassis` and `Find Local Chassis`, in that `Add Local Chassis` returns the user variables section. Since this change makes these entrypoints' signatures closer by adding the slots output, should we go one step further and add the user variables output?

**Comment by oscarfonloz** [comment]
> There is still an asymmetry between `Add Local Chassis` and `Find Local Chassis`, in that `Add Local Chassis` returns the user variables section. Since this change makes these entrypoints' signatures closer by adding the slots output, should we go one step further and add the user variables output?

I like the suggestion. I added the indicator in the same place as the Add Local Chassis and swapped the Found boolean to be on top, instead. I also added the functionality to check that the user variables ref are correct when we test the function in the unit testing VIs

**Review by rtzoeller — APPROVED** [review]

**Pull request merged**
