### PR TITLE
Scripting API for 9224 and 9228

### PR DESCRIPTION
**Pull request by Sarci1**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds support for 9224 and 9228 modules.

### Why should this Pull Request be merged?

Includes the ability to script and read back configurations for NI 9224 and NI 9228.

### What testing has been done?

Included unit tests for setting/getting the classes with get/set slot.

### CODE REVIEW

**Comment by rtzoeller** [comment]
I'm a bit confused by the changes to `Get Slot.vi`.

As far as I can tell this is the first time we've checked for a specific module class; are there other modules aside from the 9224 and 9228 that will need to take this code path in the future? Are we confident that the `conversion time` enum represents all values, or is it 9224/9228 specific?

Regarding the implementation, is there an alternative to casting specifically to that class, or are we anticipating more module-specific code like this to be added to `Get Slot.vi` in the future? I imagine this VI will get very messy if we keep adding typecasts which we expect to fail.

---

- [ ]`Create Analog Input with Conversion Time Module.vi` is complaining about its owning library not owning it. It also seems to be passing the `Analog Input Vrms Mode.lvclass` to subVI terminals which don't exist. Did your latest changes get saved and staged correctly?

**Comment by Sarci1** [comment]
> I'm a bit confused by the changes to `Get Slot.vi`.
> 
> As far as I can tell this is the first time we've checked for a specific module class; are there other modules aside from the 9224 and 9228 that will need to take this code path in the future? Are we confident that the `conversion time` enum represents all values, or is it 9224/9228 specific?
> 

We did something similar for the SD modules. I don't know of a way to do this another way as the 9224/9228 class is what is stored as a property inside the system definition. The conversion time enum, I believe, is contained to those specific modules, but I can double-check later this afternoon.

> Regarding the implementation, is there an alternative to casting specifically to that class, or are we anticipating more module-specific code like this to be added to `Get Slot.vi` in the future? I imagine this VI will get very messy if we keep adding typecasts which we expect to fail.
> 

I agree, but I don't know of an alternative unless we rearchitect how properties are stored to the system definition which would be a much larger effort. Right now the class itself is flattened into the system definition as a property.

> * [ ]`Create Analog Input with Conversion Time Module.vi` is complaining about its owning library not owning it. It also seems to be passing the `Analog Input Vrms Mode.lvclass` to subVI terminals which don't exist. Did your latest changes get saved and staged correctly?

I can look at this later today. I'm in a workshop this morning.

**Comment by Sarci1** [comment]
> * [x]`Create Analog Input with Conversion Time Module.vi` is complaining about its owning library not owning it. It also seems to be passing the `Analog Input Vrms Mode.lvclass` to subVI terminals which don't exist. Did your latest changes get saved and staged correctly?

I removed this VI. It was a relic of development prior to the move to Create.vi override methods.

**Comment by buckd** [comment]
I'm not sold on **Conversion Time** being a `Mode`. It's an additional property of an AI Module. Also, it's not exclusive to the 9224/9228. The 9212 uses the same **Conversion Time** property (although, yes, it is a separate control defined in `Modules.lvlibp:9212.lvclass`). The 9219 also uses it as part of `9219 Config.ctl`.

The 9212 is a thermocouple module with other settings that are required and the 2919 supports a bunch of different measurement types. And these are just the modules that require this property. My point is adding a new mode for each property that needs to be set for a module is not maintainable. We can't make an `Analog Input Thermocouple with Conversion Time Mode.lvclass` and an `Analog Input with Conversion Time and Other Stuff Mode.lvclass`.

Mode should represent the type of data the module is dealing with. How the module functions in order to do that isn't the mode. Module-specific configuration needs to happen in the Module class, not the Mode, unless I'm completely missing the point of `Mode`. What is the plan for extending modules with arbitrary properties set by the UI?

**Comment by Sarci1** [comment]
> I'm not sold on **Conversion Time** being a `Mode`. It's an additional property of an AI Module. Also, it's not exclusive to the 9224/9228. The 9212 uses the same **Conversion Time** property (although, yes, it is a separate control defined in `Modules.lvlibp:9212.lvclass`). The 9219 also uses it as part of `9219 Config.ctl`.
> 
> The 9212 is a thermocouple module with other settings that are required and the 2919 supports a bunch of different measurement types. And these are just the modules that require this property. My point is adding a new mode for each property that needs to be set for a module is not maintainable. We can't make an `Analog Input Thermocouple with Conversion Time Mode.lvclass` and an `Analog Input with Conversion Time and Other Stuff Mode.lvclass`.
> 
> Mode should represent the type of data the module is dealing with. How the module functions in order to do that isn't the mode. Module-specific configuration needs to happen in the Module class, not the Mode, unless I'm completely missing the point of `Mode`. What is the plan for extending modules with arbitrary properties set by the UI?

I understand the concern here. My thinking is that the setting is placed at the module level (not the channel), hence the mode for the module.

Are you thinking this should just be a property of the AI Mode and those modules that use it will set it and those that don't, don't? We'd also have to reflect what are valid options for each module in the configuration too (e.g. 9212 has High Speed/Resolution/50 Hz/etc. and not in that order, whereas the 9213 only has those first two as options).

**Comment by buckd** [comment]
My concern is we already have classes for the modules. If each module has a different set of properties that we're putting into modes, we now have two classes per module: the `Module` class and the `Mode` class.

I think the properties should be part of the module class because

> the setting is placed at the module level

The module should then use the mode information (though I don't think it's mode affects it in this case) to determine whether to set the property. This also better enables

> reflect what are valid options for each module in the configuration

The module should know its capabilities. The mode should handle returning the data in the format the module has requested. You could create different controls for the 9213 if we implemented it, like the `Modules.lvlibp` does, which would help validate the settings. I would have no problem with that, but module settings should go in the `Module` classes and properties related to how the mode returns data should go in the `Mode` classes.

You might be able to do something like add a `Set Properties` method to the module class and then call that from `Create Module.vim`, though I haven't tried that.

**Comment by Sarci1** [comment]
> My concern is we already have classes for the modules. If each module has a different set of properties that we're putting into modes, we now have two classes per module: the `Module` class and the `Mode` class.
> 
> I think the properties should be part of the module class because
> 
> > the setting is placed at the module level
> 
> The module should then use the mode information (though I don't think it's mode affects it in this case) to determine whether to set the property. This also better enables
> 
> > reflect what are valid options for each module in the configuration
> 
> The module should know its capabilities. The mode should handle returning the data in the format the module has requested. You could create different controls for the 9213 if we implemented it, like the `Modules.lvlibp` does, which would help validate the settings. I would have no problem with that, but module settings should go in the `Module` classes and properties related to how the mode returns data should go in the `Mode` classes.
> 
> You might be able to do something like add a `Set Properties` method to the module class and then call that from `Create Module.vim`, though I haven't tried that.

Ok I think I'm following @buckd. I'll try something this method a separate branch and report back.

**Comment by Sarci1** [comment]
Closing and proceeding with module properties.

**Pull request closed without merging**
