### PR TITLE
Add test for 9482 and DO conversion to Get Slot

### PR DESCRIPTION
**Pull request by oscarfonloz**
## ⚠️ This PR requires of [PR 127](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/pull/127) to be merged first

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

1. Add a test for the 9482 scripting
1. Add a subVI to the Get and Set slots tests so they're easier to debug and reuse
1. Add Digital Output conversion to Get Slot.vi

### Why should this Pull Request be merged?

Ensure the 9482 works properly when reading its settings back

### What testing has been done?

Adding an additional test and ran all scripting tests to ensure none broke

### CODE REVIEW

**Comment by rtzoeller** [comment]
- [ ] Please use a bookmark in `Get Slot.vi` (e.g. `#TODO`) to make this future work discoverable, like the previous implementation: 
image

- [ ] Can you explain when a module would not have any I/O channels? Is there an example of this?
image

- [ ] I don't think you need the default case shown below. The input is an enum: omitting the default case will cause the VI to break at compile-time if a new value is added to the enum. By having a default case, that error won't surface until run-time.
image

---

Continuing to build off the existing error code range is fine for now, but I discovered that we're unintentionally overlapping with some DSF error codes. I'm working with my team to come up with a more sustainable process long term, but as an FYI these new scripting API error codes will likely be re-assigned prior to a release.

**Comment by rdecarreau** [comment]
A note: we will have to make changes to Get Slot here to "merge" changes I made in 127.

**Comment by oscarfonloz** [comment]
> * [x]  Please use a bookmark in `Get Slot.vi` (e.g. `#TODO`) to make this future work discoverable, like the previous implementation:
>   image
Done!

> * [x]  Can you explain when a module would not have any I/O channels? Is there an example of this?
>   image
I do not know the scenario in which this would happen, but if we receive a module with no I/O I presume we would like to throw the error. I spoke about this with Lynn, since she was doing already a channel numbers check, and she agreed with the behavior.

> * [x]  I don't think you need the default case shown below. The input is an enum: omitting the default case will cause the VI to break at compile-time if a new value is added to the enum. By having a default case, that error won't surface until run-time.
>   image
You're very correct. I removed the default case.

> Continuing to build off the existing error code range is fine for now, but I discovered that we're unintentionally overlapping with some DSF error codes. I'm working with my team to come up with a more sustainable process long term, but as an FYI these new scripting API error codes will likely be re-assigned prior to a release.
I am fine with that. Let me know if you require us to provide another range of error codes :)

**Comment by rtzoeller** [comment]
> I do not know the scenario in which this would happen, but if we receive a module with no I/O I presume we would like to throw the error. I spoke about this with Lynn, since she was doing already a channel numbers check, and she agreed with the behavior.

If this is the only place the new error code is used, and we can't explain a scenario in which we would get into this state, I would prefer we either

1. Return a generic LabVIEW error code which indicates "An unexpected error has occurred"/"Internal assertion failed".
2. Repurpose `537721` to be a Scan Engine CD specific error for "An unexpected error has occurred"/"Internal assertion failed". We can then use this error code for other places where we are doing sanity checks in the custom device.

In either case, we can add additional context and the call stack to the error string.

Having a dedicated, public error code for a case we never expect to hit seems unusual to me. In any other language, this would just be a debug assert, and not be exposed via an errors file publicly.

@buckd what are your thoughts?

**Comment by oscarfonloz** [comment]
> > I do not know the scenario in which this would happen, but if we receive a module with no I/O I presume we would like to throw the error. I spoke about this with Lynn, since she was doing already a channel numbers check, and she agreed with the behavior.
> 
> If this is the only place the new error code is used, and we can't explain a scenario in which we would get into this state, I would prefer we either
> 
> 1. Return a generic LabVIEW error code which indicates "An unexpected error has occurred"/"Internal assertion failed".
> 2. Repurpose `537721` to be a Scan Engine CD specific error for "An unexpected error has occurred"/"Internal assertion failed". We can then use this error code for other places where we are doing sanity checks in the custom device.
> 
> In either case, we can add additional context and the call stack to the error string.
> 
> Having a dedicated, public error code for a case we never expect to hit seems unusual to me. In any other language, this would just be a debug assert, and not be exposed via an errors file publicly.
> 
> @buckd what are your thoughts?

That logic makes sense to me. Does Error 42 work for you @rtzoeller? I did not find a LabVIEW generic for "internal assertion failed" and didn't like Error 1 because it's not quite an argument what is failing in the function, but a wrong state of the class' internal data.

image

**Review by buckd — COMMENTED** [review]
- [ ] I'd prefer to use error -124201 instead of error 42.
image

**Comment by oscarfonloz** [comment]
> * [x]  I'd prefer to use error -124201 instead of error 42.

Deal! Fixed :)

**Review by buckd — APPROVED** [review]
Waiting on last look from @rtzoeller to merge.

**Review by rtzoeller — APPROVED** [review]

**Pull request merged**
