### PR TITLE
Fix #45: Window reboots when importing 3rd party EtherCAT profile

### LINKED ISSUE #45: Importing a 3rd party EtherCAT slave ESI file reboots host computer (if target is not configured yet)
**Describe the bug**
When importing a 3rd party EtherCAT slave ESI file the target gets rebooted. This is fine this is a RT target. However if a user has not configured target address yet, then the import will reboot the host computer. 

**To Reproduce**
1. Create a new system definition (do not configure ip address of target)
1. Add Scan Engine EtherCAT custom device
1. Import 3rd party EtherCAT slave ESI file
1. Reboot!

**Expected behavior**
Do not reboot host computer.

### PR DESCRIPTION
**Pull request by Karl-G1**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Modified the Action VI that imports 3rd party EtherCAT profiles to Windows and RT Targets to check which OS the RT Target is set to before attempting to connect to the RT target and rebooting. 

### Why should this Pull Request be merged?

Fix #45 

### What testing has been done?

Built and tested the custom device locally for VeriStand 2017.

### CODE REVIEW

**Comment by rtzoeller** [comment]
- [ ] Use either the VeriStand-provided `NI VeriStand - Get Target Type.vi`, or the home-grown `NI VeriStand - Get Target Operating System.vi` to query the target OS. You can then remove `Get Target Operating System.vi`.

- [ ] There is some other work done in that same event to handle importing to the RT target. We should "AND" that with the Windows and IP address check as well, so that we don't do extra work in the case that it is the local host (and to single source the check).

image

**Comment by rtzoeller** [comment]
@Karl-G1 before this gets merged, please update your pull request text to reflect the current status. The "What" section is outdated.

**Comment by Karl-G1** [comment]
> @Karl-G1 before this gets merged, please update your pull request text to reflect the current status. The "What" section is outdated.

Complete.

**Comment by Karl-G1** [comment]
Reviewer note:
The True constant in the False case of the case structure that was modified is intentional. It merely blocks launching a dialog warning of rebooting the RT target if you proceed.
image
image

**Pull request merged**
