### PR TITLE
Add method to copy slots

### PR DESCRIPTION
**Pull request by oscarfonloz**
# :warning: [PR 141](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/pull/141) must be merged first into main.

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adding method to the scripting API to copy slots. 

### Why should this Pull Request be merged?

This makes it easier for users to use existing modules in other slots without having to read and write them manually.

### What testing has been done?

Ensured all the unit tests pass and added one for each function.

### CODE REVIEW

**Comment by rtzoeller** [comment]
Providing feedback on the tool itself now, as even though the other VIs conflict, the tool can be reviewed independently.

- [ ] Error 7, which occurs if the library path is invalid, seems like it should also be listed as a recoverable error.
- [ ] ~~Why is the 5xxx range listed as recoverable?~~ Ahh, I see that you're using it for your own errors throughout the application. Probably worth mentioning in `Error Handler.vi`, like with Error 43.
- [ ] `Import from CSV.vi`'s icon claims it is `Export to CSV.vi`.
- [ ] I'm not understanding the usage of "This VI" as the default value in `Save Documentation to VIs.vi`.
- [ ] I don't believe you need to read/specify the VI path in `Save Documentation to VIs.vi`. Leaving the path unspecified should save it in place.
- [ ] Clicking Load Library should unload any loaded VIs first. I loaded a few different libraries and observed that all previously loaded VIs stayed in memory, despite not appearing in the list of VIs.

I'm glad you aren't saving VIs which already match the description!

**Comment by rtzoeller** [comment]
I'm not generally opposed to the creation of utility methods such as these, since it's possible they help solve a specific use case. That said, it'd be helpful to understand the context for when you expect these VIs to be used.

Is scripting the copying, swapping, or moving of modules _without_ access to the program that scripted the original system definition something you expect to be common? If modules have changed locations, I imagine it would be easier to just update and re-run the original scripting code to use the new locations, rather than write a second program to patch them.

**Comment by rtzoeller** [comment]
`Swap Slot.vi` (and by extension `Move Slot.vi`) appears to work in my minimal testing, but I'm worried the implementation is going to subtly break something. At best, the end result is confusing.

Up until now, there has been an invariant that the order of the slots in the system definition aligns with the values of the slot number properties. This change appears to violate that invariant, and I'm not sure where in the custom device that invariant might be relied on.

I created an instance of the custom device by hand, added a module to slot 1, and then tried to use `Move Slot.vi` to move that module to slot 2. The result can be seen below; it's still the first slot under the local chassis, and still named "Slot 1", but the associated property claims it is slot 2. The result can still be deployed (at least with only one module present), but it's obviously not intuitive behavior.

image

We should maintain the "system definition order is the slot order" invariant.

**Comment by oscarfonloz** [comment]
I'm gonna need to put some thought into this one. I would prefer to keep them if I can, but I'll check with @debryant and @Sarci1 the use cases, and consider if fixing the Slot naming would be too challenging.

**Comment by oscarfonloz** [comment]
@rtzoeller I spoke with @debryant and we agreed that not all these utilities will be needed for our use case. Therefore, I am removing both Move Slot and Swap Slot, because they leave the system definition file in a bad state and we don't want to invest time right now in them.

**Comment by rtzoeller** [comment]
- [ ] `Set Slot.vi` needs to be updated to take advantage of the new helper functions.

The rest of the changes look good.

**Comment by rtzoeller** [comment]
@oscarfonloz on further inspection, it's probably also worth renaming `Swap Slot.vi` to `Swap Slots.vi`, since it operates on two slots.

**Comment by debryant** [comment]
The Swap and Move VIs are removed from this PR. The Copy VI remains. Correct?

**Comment by rtzoeller** [comment]
@debryant yes; thanks for catching that.

**Comment by oscarfonloz** [comment]
> * [x]  `Set Slot.vi` needs to be updated to take advantage of the new helper functions.
> 
> The rest of the changes look good.

Updated, thanks!

**Review by rtzoeller — APPROVED** [review]

**Pull request merged**
