### PR TITLE
add 9422 scripting

### PR DESCRIPTION
**Pull request by rdecarreau**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Add 9422 module and tests, also added DI mode test class.

### Why should this Pull Request be merged?

New module support for 9422

### What testing has been done?

Ran VI Tester locally

### CODE REVIEW

**Comment by rtzoeller** [comment]
@rdecarreau please update the PR name to something other than the branch name. Thanks!

**Comment by rtzoeller** [comment]
- [ ] `Convert Module Model to Module Class.vi` needs to be updated to handle the 9422.

**Comment by rdecarreau** [comment]
> * [ ]  `Convert Module Model to Module Class.vi` needs to be updated to handle the 9422.

Completed.

**Comment by rdecarreau** [comment]
I also added a lot to the DI mode which was left off the other DI Mode PR. Added a test set-get slot VI for 9422.

**Comment by rtzoeller** [comment]
- [ ] Please ensure the cases in `Convert Module Model to Module Class.vi` are ordered numerically.

- [ ] Add the new module test class to the project, in the same location as the other module test classes.

**Comment by rdecarreau** [comment]
> * [ ]  Please ensure the cases in `Convert Module Model to Module Class.vi` are ordered numerically.
> * [ ]  Add the new module test class to the project, in the same location as the other module test classes.

Updated both items.

**Review by rtzoeller — APPROVED** [review]

**Pull request merged**
