### PR TITLE
Bugs #33 and #15

### PR DESCRIPTION
**Pull request by VincentRuault**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

VI "Host - Get Local and ECAT Masters.vi" modified to solve bug #33 and implement a workaround for bug #15. Idea is to give a better user-experience to end-user and better guide him.

### Why should this Pull Request be merged?

For "slow" modules, taking more time and throwing 65700 error, we exit right away during parsing and retry later with a maximum number of retries.

For error "65704", as CAR #729217 is long-time deferred, I propose following: detect 65704 error and if it happens. open a dialogue window to user, asking to do a deployment before redo an Auto-Detect or add manually missing cRIO modules in local chassis. Note that we don't exit right away (when error 65704 is thrown), we go through to the entire list of variables to parse. 

### What testing has been done?

With a NI-9214 located in a NI-9040 chassis, I checked that the NI-9214 is detected at first auto-detect.

### CODE REVIEW

**Comment by csjall** [comment]
- [ ] This bug fix injects a lot of changes into Custom Device Source/System Explorer/Utility/Target Communication/Host - Get Local and ECAT Masters.vi. I propose we keep retain the original code and create a new subVI that repeatedly calls Host - Get Local and ECAT Masters. Be sure to add a delay in the error case so that we give the hardware some time to spin up.

image

Writing a wrapper around the existing implementation should allow us to easily remove this workaround in the future if we come up with a solution in the driver.

- [ ] Custom Device Source/System Explorer/Utility/Target Communication/Host - Get HW Config.vi has no substantial changes. Revert this change. We only want to submit substantial changes.

**Comment by VincentRuault** [comment]
Hi @csjall,

Thank-you for your answer. 

- For **65700** error, I think I see what you mean but, still, it will take a modification of the function "Host - Get Local and ECAT Masters.vi" because there is no shift register for the error cluster, right? Though, I agree, it's really limited in terms of modification. To confirm, your code snippet shows case for 65704 where it would be more for 65700, right?
- For **65704** error,  what do we want to do? Do we want to return partial list of modules detected successfully or we return at first 65704 error?

Regards

**Comment by csjall** [comment]
> Hi @csjall,
> 
> Thank-you for your answer.
> 
> * For **65700** error, I think I see what you mean but, still, it will take a modification of the function "Host - Get Local and ECAT Masters.vi" because there is no shift register for the error cluster, right? Though, I agree, it's really limited in terms of modification. To confirm, your code snippet shows case for 65704 where it would be more for 65700, right?
> * For **65704** error,  what do we want to do? Do we want to return partial list of modules detected successfully or we return at first 65704 error?
> 
> Regards

You are correct. I was referring to 65700 in that case.

For error 65704 we should just throw up the dialog, at the top level VI. The 2nd auto detect is going to clear all the hardware anyway, so we will get all the hardware on subsequent calls.

How long does it take for the 9214 to spin up? Are we talking milliseconds, seconds, or tens of seconds?

**Comment by VincentRuault** [comment]
Hi @csjall 
I reverted previous changes and submitted a new commit in which I took a different approach. VI are in 2017 version.
I did some tests with that new CD version (I just recompiled Configuration part on 2018 as it's my customer's version) and check that we can detect the NI-9214 (at first auto-detect) and also that the pop-up is displayed when error 65704 happens under the hood.
Regards

**Comment by csjall** [comment]
Minor tweaks:
image

- [ ] Pull the retry code into a subVI and call it from Host - Get HW Config.vi. See my example above. The ultimate goal is to have with minimal code. This follows the principle of "Clean Code" to make small blocks of code that is easier to read and maintain. I highly recommend [the book](https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882) if you have not read it yet.

- [ ] Collapse 0, Default, and 65704 case into single structure as they all have the same implementation.

**Comment by VincentRuault** [comment]
Hi @csjall 

Just to confirm, what you call the retry code is the "For" loop, right? Side question: where do we put the limit to create a new sub-VI or not (insert extra code in caller VI instead)? What name do you want?
Thank-you for the book reference.
 
Regards

**Comment by csjall** [comment]
> Hi @csjall
> 
> Just to confirm, what you call the retry code is the "For" loop, right? Side question: where do we put the limit to create a new sub-VI or not (insert extra code in caller VI instead)? What name do you want?
> Thank-you for the book reference.
> 
> Regards

The for loop and the error handler should all move into a single subVI. Name it "Host - Get Local and ECAT Masters with Retries.vi". The idea is that it is a superset of Host - Get Local and ECAT Masters. 

Where is the limit? In my opinion block diagrams should be compact: easily fitting on your screen and simply calling into other subVIs. If I have to scroll a block diagram on a 1080p display, then it's too much code in a single VI. Here are some examples from system monitor. I have seen plenty of custom devices that create all the channels in the top level Initialization VI. Instead this breaks it down into multiple smaller blocks.

image

image

image

image

**Comment by VincentRuault** [comment]
Following things should be address in commit: 8aeb4c9 I just did.

> Minor tweaks:
> image
> 
> * [x]  Pull the retry code into a subVI and call it from Host - Get HW Config.vi. See my example above. The ultimate goal is to have diagrams with minimal code. This follows the principle of "Clean Code" to make small blocks of code that is easier to read and maintain. I highly recommend [the book](https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882) if you have not read it yet.
> * [x]  Collapse 0, Default, and 65704 case into single structure as they all have the same implementation.

**Pull request merged**
