### PR TITLE
Adding Scripting API Support for 9212 and 9213

### PR DESCRIPTION
**Pull request by Sarci1**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds the ability to create a 9212 or 9213 module in the scripting API and read the configuration back.

Changes the Create Default Channel Array.vim to include a default settings input, allowing the user to define what should be instantiated in the array in the event the channels settings array is empty.

### Why should this Pull Request be merged?

Adds support for the 9212 and 9213.

### What testing has been done?

Validated that all custom device unit tests continue to run including newly created ones for these two modules.

### CODE REVIEW

**Review by buckd — COMMENTED** [review]
- [ ] What are the changes to `Custom Device Scan Engine.xml` and why were they made? I was able to determine one of the changes was making one of the actions non-modal, but I don't understand why that change is necessary for 9212/13 scripting.
- [ ] Why are there changes to all the `Mode` classes in this PR? It should be limited to 9212/13 and Thermocouples. Maybe the base Analog Input too, but I don't see why this should modify digital modes. If this is due to the change in `Create Default Channel Array.vim`, I would like to have that change in a different PR so both changes are easier to digest and document.
- [ ] `Convert Channel Settings to Thermocouple.vi` is not part of the `Scan Engine Scripting.lvlib`.
- [ ] Please order the cases in `Get Slot.vim`.
image

I like this and it was one of the things I had in mind on the last review for preventing this VI from becoming a bottleneck. Seems like we could have a dynamic dispatch VI in `Module.lvclass` that could take in the `RSI Module` and handle all of the conversion without needing the case structure for the module. We don't need to change it now, but can you create an **enhancement** issue on the repo so we can look at this at a later date?

**Comment by oscarfonloz** [comment]
FYI: @Sarci1 is OOO for the rest of the year and I will be taking over for her to address the comments and have this PR submitted

**Comment by Sarci1** [comment]
@oscarfonloz I didn't change the XML intentionally so I don't know what that's about. You can probably revert it. As for the modes, I expect the same regarding the *.vim

**Comment by oscarfonloz** [comment]
> * [x]  What are the changes to `Custom Device Scan Engine.xml` and why were they made? I was able to determine one of the changes was making one of the actions non-modal, but I don't understand why that change is necessary for 9212/13 scripting.

Reverted this change

> * [ ]  Why are there changes to all the `Mode` classes in this PR? It should be limited to 9212/13 and Thermocouples. Maybe the base Analog Input too, but I don't see why this should modify digital modes. If this is due to the change in `Create Default Channel Array.vim`, I would like to have that change in a different PR so both changes are easier to digest and document.

Yes, the vim changed all the creation VIs to add the default settings. From my message in Teams: "_I am concerned this request will delay too much the PRs to go in. Do you have a chance to review the two separate PRs tomorrow if I were to make the change? I am assuming you're taking vacation already, and we want to keep making as much progress as we can while some of us are still in office. This will likely mean ending up with a couple of separate and stacked PRs, but this one touches all the modes, so it might be a good idea to pass it quick_"

> * [x]  `Convert Channel Settings to Thermocouple.vi` is not part of the `Scan Engine Scripting.lvlib`.

Good catch! I added it to the library under the Utility virtual folder

> * [x]  Please order the cases in `Get Slot.vim`.
>   image
> 
> I like this and it was one of the things I had in mind on the last review for preventing this VI from becoming a bottleneck. Seems like we could have a dynamic dispatch VI in `Module.lvclass` that could take in the `RSI Module` and handle all of the conversion without needing the case structure for the module. We don't need to change it now, but can you create an **enhancement** issue on the repo so we can look at this at a later date?

I agree and opened [Issue 138](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/issues/138) to track this enhancement.

**Comment by oscarfonloz** [comment]
I believe the build is failing because we're missing the module's accessors from [PR 40](https://github.com/ni/niveristand-scan-engine-module-libraries/pull/40), let me know if this is not correct.

**Comment by buckd** [comment]
> * [ ]  Why are there changes to all the `Mode` classes in this PR? It should be limited to 9212/13 and Thermocouples. Maybe the base Analog Input too, but I don't see why this should modify digital modes. If this is due to the change in `Create Default Channel Array.vim`, I would like to have that change in a different PR so both changes are easier to digest and document.

Given the substantial progress made on code changes over the holidays, I will acquiesce and we can put this change in on this PR, but please add information to this pull request that tells us this change was made in this PR because it is not really related to the description and intent of this PR.

> * [ ]  Please order the cases in `Get Slot.vim`.
>   image

These still need to be ordered.

**Comment by oscarfonloz** [comment]
Thanks for the comments @buckd 

> > * [x]   Why are there changes to all the `Mode` classes in this PR? It should be limited to 9212/13 and Thermocouples. Maybe the base Analog Input too, but I don't see why this should modify digital modes. If this is due to the change in `Create Default Channel Array.vim`, I would like to have that change in a different PR so both changes are easier to digest and document.
> 
> Given the substantial progress made on code changes over the holidays, I will acquiesce and we can put this change in on this PR, but please add information to this pull request that tells us this change was made in this PR because it is not really related to the description and intent of this PR.
> 

@Sarci1 helped me adding the note about this VI to the PR's description

> > * [ ]   Please order the cases in `Get Slot.vim`.
> >   image
> 
> These still need to be ordered.

It shows ordered in my side for this commmit. 
I cleared the compiled object cache in my machine, since I noted it started doing "weird things" when loading items from previous commits. Is this not what you see?

image

**Review by buckd — APPROVED** [review]

**Pull request merged**
