### PR TITLE
Added support for DBL and SGL 3rd party IOV types

### PR DESCRIPTION
**Pull request by fmussi**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Fix for #19. It adds support for SGL/DBL I/O variable datatypes on 3rd party EtherCAT slaves. Some EtherCAT slaves define the IO variables (PDO) with float/real data type within the ESI .xml file. The custom device must recognize it and manage properly, as LabVIEW and NI-Indcomm ethercat driver already support such data types.

- Extended typedefs Custom Device Source\Type Defs\ECAT Channel Data Type.ctl and \Custom Device Source\Type Defs\UDV Data Type.ctl to manage DBL and SGL
- Added cases to Custom Device Source\System Explorer\Utility\TypeCodeToEnum.vi
- Added cases to scanned R/W VIs on RT driver.

### Why should this Pull Request be merged?

This pull request implements little modification to the existing code base and does not change or modify other parts of the code. Also, 3rd party slave are already supported by the custom device

### What testing has been done?

- Tests done with a real 3rd party EtherCAT slave that export _REAL_ datatypes as I/O (PDO) variables
- Verified that the System Explorer correctly recognizes SGL variables
- deployed a system definition file and verified that SGL / DBL data are correctly read and mapped to channels.

### CODE REVIEW

**Comment by csjall** [comment]
@fmussi We are finishing up the current release of Scan Engine Custom Device. As a result this change will not make it into the installer until next release. However we will review these changes and get it into master as soon as possible.

**Comment by csjall** [comment]
- [ ] Remove the manual tests from the project. If these tests are necessary, then add it to automated unit tests.
image
- [ ] There are several added labels with the words "need to". Is this a comment or an outstanding action item?
image
- [ ] Revert unchanged files. Some files like `Get Generic Slave Data.vi`, `Get Target IP Address.vi`, `Main - Auto Detect Modules.vi`, and `Set FPGA Mode.vi` have no changes in the visual diff. Ideally we should only submit files that have changes from master.

**Comment by csjall** [comment]
@fmussi Once @rtzoeller approves this change we will merge it into master.

**Comment by rtzoeller** [comment]
I believe @csjall's intent was for the manual tests to be removed entirely from the repository if they were not going to be converted to automated tests.

You can revert the VIs without any meaningful changes by checking out the version of those files as they exist currently on our master. For example, 
```
git checkout 7ecabfae02d36853fde4435faf4cdfeae62d1a1e -- "Custom Device Source\System Explorer\Utility\Set FPGA Mode.vi"
```

**Comment by fmussi** [comment]
I Removed the manual test files. I think I just miss to revert some file, but I don't have the most updated list

**Pull request merged**
