### PR TITLE
Add scripting mechanism to clear a slot

### PR DESCRIPTION
**Pull request by oscarfonloz**
## ℹ️ This PR branches from NI\main

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

We want a way to "empty" an existing slot in the system definition file

### Why should this Pull Request be merged?

This PR adds a function that allows us to assign an empty module to a slot that already has a module assigned to it. The method clears the slot's child items, sets an empty module and updates both the name and the GUID.

### What testing has been done?

Added a new unit test that checks that Clear Slot does, in fact, remove a module from a slot once it has been assigned.
Ensured all previous unit tests passed.

### CODE REVIEW

**Comment by oscarfonloz** [comment]
The original requirement was to create an "Empty Slot" class, but I do not see the need for one knowing that what we want to accomplish is to remove modules from slots. Therefore, I prefer a simpler approach than adding a new class just for the sake of it 😄

**Comment by rtzoeller** [comment]
- [ ] The implementation of `Clear Slot.vi` is duplicated almost exactly from the existing implementation of `Set Slot.vi`. Please create a subVI that both of these VIs call, so we don't duplicate this logic. Note that `Set Slot.vi` calls `Create Channels.vi`, while `Clear Slot.vi` does not.

image
image

**Comment by oscarfonloz** [comment]
> * [ ]  The implementation of `Clear Slot.vi` is duplicated almost exactly from the existing implementation of `Set Slot.vi`. Please create a subVI that both of these VIs call, so we don't duplicate this logic. Note that `Set Slot.vi` calls `Create Channels.vi`, while `Clear Slot.vi` does not.
> 
> image
> image

You're right @rtzoeller, I found that and added a subVI in [PR 145](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/pull/145). I did not touch **Set Slot.vi** because that VI is used in the other PRs and would have created a conflict. Are you fine in me making this replacement at the end? Else I will do it here and we'll deal with it somehow 🙄

**Comment by rtzoeller** [comment]
@oscarfonloz I'm fine with deferring that change for developer efficiency.

**Review by rtzoeller — APPROVED** [review]
Note that we will need to update the palettes.

**Pull request merged**
