### PR TITLE
Pull Request to address Issue #12

### PR DESCRIPTION
**Pull request by VincentRuault**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

The changes are here to align the new "Slot Programming Mode" property  for NI-904x and NI-905x families to the setting set in Target Main Configuration page by control "FPGA / Scan mode...". Modifications done are applied during AutoDetect and also in ActionVI called at deploy.

### Why should this Pull Request be merged?

Cf. Issue #12 It's not customer's specific. It would be beneficial to all users of these new families, not break existing features.

### What testing has been done?

Tested with NI-VS 2018 only.
I had a NI-9049 with 3 C-Series modules inside and also a NI-9145 attached to it. I did couple of tests (switch from one mode "FPGA" to "Scan Mode" and vice-versa) and checked that modules from Local Chassis are detected correctly when set in Scan Mode. Same test done with NI-9040 chassis, same local modules and a NI-9145. I also tested a NI-9082 (PharLap based), kind of non regressive testing.

### CODE REVIEW

**Comment by rtzoeller** [comment]
Thanks @VincentRuault for the pull request; can you please fill out the pull request template (replace the TODOs)?

**Comment by rtzoeller** [comment]
@VincentRuault the diff-bot is showing some files in this pull request as being functionally unchanged, but updated due to how LabVIEW saves files. Can you verify that you meant to include these files in the pull request, and if not can you reset them?

The files I see which have not changed are:
- `Set FPGA Mode.vi`
- `Is Synced to Scan.vi`
- And possibly `Main - Auto Detect Modules.vi`

You can reset a file to the state from a previous commit with `git checkout commit_hash -- filename`, e.g. `git checkout 6f3ad96545531e1f551f508bab82c926d22d1037 -- "Custom Device Source/System Explorer/Utility/Set FPGA Mode.vi"` to reset to the current top of our master.

**Comment by VincentRuault** [comment]
Hi @rtzoeller,

I confirm I haven't touched the 2 files:
The files I see which have not changed are:
Set FPGA Mode.vi
Is Synced to Scan.vi
The file: Main - Auto Detect Modules.vi has been touched (I added call to my new sub-VI).
I'm using Sourcetree and I need to understand where I can do that from the environment or via command line.

Regards

**Comment by rtzoeller** [comment]
I am not familiar with Sourcetree, however what you are wanting to do is check out the version of a file from a previous commit, and then commit that previous version of the file so that it appears unmodified.

The git command line operation to check out the previous version of those two files is: 

- `git checkout 6f3ad96545531e1f551f508bab82c926d22d1037 -- "Custom Device Source/System Explorer/Utility/Set FPGA Mode.vi" "Custom Device Source/System Explorer/Utility/Set FPGA Mode.vi" "Custom Device Source/System Explorer/Utility/Is Synced to Scan.vi"`

After checking out those files, you can commit them and update this pull request.
- `git add "Custom Device Source/System Explorer/Utility/Set FPGA Mode.vi" "Custom Device Source/System Explorer/Utility/Set FPGA Mode.vi" "Custom Device Source/System Explorer/Utility/Is Synced to Scan.vi"`
- `git commit -m "Restore unmodified files"`
- `git push`

**Comment by VincentRuault** [comment]
Hi @rtzoeller,

I made a new commit to integrate your changes:

- I defined a TypeDef for the FPGAScanInterfaceMode to not deal with Integer Value and it's now passed to sub-VI.

- To be dependent to an input list or a global, I discovered that SystemConfiguration API doesn't return same items depending on cRIO type, I did tests with cRIO-904x controllers but also NI-9068 and a NI-9082. The NI-906x and NI-908x don't support Slot Programming Mode. Only with cRIO-904x, I was getting set of properties to play with SlotProgramming Mode property.  Where it looks OK, I would like to get a confirmation but from which NI team? It's something I observed but not something I had read before testing.

- I adjusted connector panes.

- I couldn't revert to previous version only the 2 files you asked, So, I reverted the entire Commit.-

**Comment by rtzoeller** [comment]
I built the custom device and ran the existing tests successfully.

I would like to see a test added in the same vein as the existing ones for combo devices, so that we can validate this fix does not break in the future. I envision that test doing the following (assuming a 9045 with three 9401s in the same setup as the specialty digital tests):

1. Configure one module in DAQmx mode, one module in scan mode, and one module in FPGA mode.
1. Deploy a system definition with all three modules added; it should switch them all to scan mode as part of deployment.
1. Undeploy after waiting for some time.
1. Read back the module modes and assert that they are in scan mode.
1. If they weren't converted to scan mode, set them back manually so other tests don't fail.

@VincentRuault do you feel comfortable expanding the existing tests to add this one? If not, I can add the test and contribute it to the pull request.

**Comment by VincentRuault** [comment]
Hi Ryan,
No problem to add the test. Where do I add it? Is-it in the "What testing has been done?" section in the first post?

**Comment by rtzoeller** [comment]
Sorry, I wasn't particularly clear. I was referring to adding an automated test built on top of the 
 [testing tools](https://github.com/ni/niveristand-custom-device-testing-tools). There are existing tests in the `Scan Engine - Tests.lvproj` project, which make use of VI Tester to run automated tests.

There is some documentation in the custom device testing tools repository and the other tests in this repo are decent examples. I am happy to write the test if that is easiest.

**Comment by rtzoeller** [comment]
- [ ] @VincentRuault can you explain what errors you expect to occur when getting the System Hardware Expert in `Align cRIO Programming Mode.vi`? 
image
I am trying to understand what errors could occur (and if we can safely ignore them). We should not be clearing all errors unconditionally, since this will hide legitimate issues.

- [ ] What is the motivation for ignoring errors inside the property nodes?


Minor nitpick: the error in terminals do not need to be marked as required, and can be marked as recommended.

**Comment by rtzoeller** [comment]
I can add an automated test for this validation.

**Comment by rtzoeller** [comment]
- [ ] Should this be "all values match"? I believe this would remove the need to filter things (like network devices) out.

image

**Comment by VincentRuault** [comment]
I just commit a new version of the Align Programming Mode.vi.

I followed the idea to use "all values match" and dig more with extra criterias for the filter. It now allows to retrieve only slots supporting "Slot Programming Mode" property. It simplifies a lot the logic behind.

I changed connector pane Error In to be Recommended.

About Test VI, I haven't had time to look at that. It might be faster if you created the Test yourself. I had a quick look and I installed Testing Tool repository but I'm still missing some Packages and read the documentation before doing anything.

**Comment by rtzoeller** [comment]
I like the implementation cleanup!

Two things:
 - [ ] We should only update the FPGA Scan Interface Mode for modules present in the custom device; any slots not in the custom device should be untouched. Right now we set the mode for all modules, meaning we will take modules used by other custom devices or parts of the system out of their existing modes, e.g. X-NET modules will be broken. 

- [ ] (Minor) You have boolean wires running behind a case structure and overlapping other wires, which makes it unclear how things are connected.
image

**Comment by rtzoeller** [comment]
One more minor thing:
- [ ] Passing the expert into `FindHardware` is measurably faster than passing it into the property node. Passing it into `FindHardware` will restrict our search to that expert, while passing it into the property node will result in it searching all of the experts and filtering them out.

**Comment by VincentRuault** [comment]
I'll fix wiring and also change how to specify the expert.

About your comment: _"We should only update the FPGA Scan Interface Mode for modules present in the custom device; any slots not in the custom device should be untouched. Right now we set the mode for all modules, meaning we will take modules used by other custom devices or parts of the system out of their existing modes, e.g. X-NET modules will be broken."_Is you comment limited to XNET? Because I don't really see any other Custom Device, correct me if I'm wrong. In terms of limitations, how would you envision that? Should we detect XNET modules Serial modules and not update them?

**Comment by rtzoeller** [comment]
No, it should not just be limited to XNET.

Imagine that I have a cRIO with 8 slots, all of which are populated. I want to use the Scan Engine EtherCAT custom device with slots 1-3, but use other custom devices or control methods for slots 4-8. They could be X-NET, DAQ, or any other module type. In this case, the custom device would only have slots 1-3 populated in the local chassis; the other slots would be listed as empty. You should use the populated status of the chassis in the custom device to determine which slots to update.

The status of which modules are populated in the custom device is saved in the system definition; you can use the "Local Chassis" GUID (look in `Scan Engine GUIDS.vi`) to find the chassis, and then look at the children of that to find the ones with the "Slot" GUID. From there, you can use the methods on the module to get the slot number (look at `Scan Engine Slot Page.vi` to see how it is done there).

**Comment by VincentRuault** [comment]
Do you confirm that we are not distinguishing the changes to be applied during _Auto-Detect of the Configuration_ and during _actual Sysdef Deployment_, right? I would imagine that during Auto-Detect of the Configuration, we can be systematic* but during Deployment, that's when we need to take into account which slots are actually handled by SEEC CD. Am-I right?

* I'm assuming that, after SEEC CD Configuration Auto-Detect, user will configure other CDs or DAQ tasks, potentially affecting some slots handling. Valid assumption?

**Comment by rtzoeller** [comment]
We should not change the scan mode during auto-detect at all. We are detecting what is in the system at this point, not modifying it.

This reconfiguration should only be run during deployment, since at this point the user has explicitly told the custom device which modules it owns (by adding them to the custom device).

**Comment by rtzoeller** [comment]
@VincentRuault I tried this on a 9045 and the functionality worked as expected! Thank you again

I will test this on other controllers/chassis tomorrow. I am not planning on contributing an automated test to this pull request; https://github.com/ni/niveristand-custom-device-testing-tools/issues/33 is blocking the test I have written from being generic.

**Comment by rtzoeller** [comment]
I am not sure why me pushing closed this pull request. I will open another one with the same changes, since I can't re-open this one.

**Pull request closed without merging**
