### PR TITLE
Create a source distribution build specification for the scripting API

### PR DESCRIPTION
**Pull request by debryant**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Create a post-build step to copy the VIs to the correct location in vi.lib (vi.lib\addons\VeriStand Custom Device Scripting APIs)
Added a space holder top level palette file in order to include/verify palette files as part of this build spec.

Note: I had to include/exclude specific VIs from the Scan Engine Custom Device.lvlib since the "shared" VIs are not architected to be in a separate lvlib. (This was with prior direction and agreement from Ryan & Donovan with the understanding that it is not the purpose of this project to reorganize the Scan Engine Custom Device.lvlib.)

### Why should this Pull Request be merged?

Need to collect all the VIs needed for using the scripting VIs into one place in preparation for building a package file for this purpose.

### What testing has been done?

Dropped all the top level scripting VIs from the vi.lib Scan Engine Scripting directory to verify all dependencies are found and VIs load in a good state.

### CODE REVIEW

**Comment by rtzoeller** [comment]
- [ ] We need to enable building this new build specification on the build machine. That doesn't necessarily need to be in scope for this PR, but it seems like a good opportunity and should be a trivial change. You would just add something like the following to the `build.toml` file.

```
[[build.steps]]
name = 'Scripting API'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Scripting API'
dependency_target = 'Pharlap'
```

It makes sense to build this immediately after the `Configuration Library` build spec is built, so that is where I would recommend adding it in `build.toml`.

- [ ] Update the palette file to be titled `Scan Engine` and remove the contained items. I'm fine with having a placeholder palette file for now, but it was confusing when I couldn't even find the placeholder due to the name.

- [ ] I was surprised at the number of individual VIs listed as `Always Excluded`. Were these actually being pulled in, or was adding them to `Always Excluded` done preemptively?

- [ ] Remove the loop from `Copy Scripting API to Installed Location.vi`, unless we anticipate installing multiple directories (I don't think we do).

**Comment by debryant** [comment]
> We need to enable building this new build specification on the build machine.

I have a follow-up PR in the sidelines that includes the build.toml & control scripting files. I am waiting on this one to be complete 1st (esp since this one is substantial in its build spec change and still requires merging in Lynn's project/library changes)., then I will submit/test that one by itself. I will verify the placement of the build_step is as you suggest.

**Comment by debryant** [comment]
> I was surprised at the number of individual VIs listed as Always Excluded. Were these actually being pulled in, or was adding them to Always Excluded done preemptively?

Yes, all these files from lvlib were getting pulled in b4 I purposefully excluded them, including those VIs which are only ever dynamically called by VS, like the Page VIs. I don't know why. I noticed that neither the R&F nor the InstrAddon build specs needed to exclude VIs, but neither of these had dependencies on VIs sets that included the System Explorer or Engine VIs.
Ideas?

**Comment by rtzoeller** [comment]
> Yes, all these files from lvlib were getting pulled in b4 I purposefully excluded them, including those VIs which are only ever dynamically called by VS, like the Page VIs. I don't know why. I noticed that neither the R&F nor the InstrAddon build specs needed to exclude VIs, but neither of these had dependencies on VIs sets that included the System Explorer or Engine VIs.
Ideas?

I'll take a look and see if I can figure anything out!

**Comment by rtzoeller** [comment]
A few thoughts:

The only item in `Scan Engine Custom Device.lvlib:System Explorer/Action VIs` that we are pulling in is `Main - On Delete.vi`, which raises the question "Why are we pulling that in at all?". It turns out `Scan Engine Scripting.lvlib:Remove Scan Engine Custom Device.vi` is calling that VI directly. A better architecture would probably be to refactor the common logic from that action VI out into a helper, and have both `Main - On Delete.vi` and `Remove Scan Engine Custom Device.vi` call the helper directly; we can then fully exclude the action VIs directory. This isn't in scope for this PR.

Ultimately, I'm not sure this pull request needs to do a fine-grained exclusion of anything. It definitely makes sense to exclude the `RT` directory as you've already done, but I'm not sure what the harm is if we accidentally pull in some extra System Explorer-related VIs. We aren't intending for customers to call into this LLB directly, and aren't guaranteeing compatibility for the VIs in it. If it's just a few extra MBs on disk, I'm not sure it's worth the maintenance hassle for us to try to filter out individual VIs (especially since we're all but guaranteed to forget to do this for new VIs in the future).

My recommendation would be to remove the exclusions, with the exception of the `RT` directory since we know we never want to include those.

---

Oh, I just noticed that "Remove unused members of project libraries" isn't checked for this build specification, but is for the other Scan Engine build specs. That's likely a big part of the reason you're needing to manually pull things in. We might not need any exclusions at all with that checked.

**Comment by debryant** [comment]
> The only item in Scan Engine Custom Device.lvlib:System Explorer/Action VIs that we are pulling in is Main - On Delete.vi, which raises the question "Why are we pulling that in at all?".... This isn't in scope for this PR.

I noticed this too, and similarly bit my tongue to not address it as part of this PR. I created AzDO Task 1175321 "Refactor Remove Scan Engine Custom Device.vi so doesn't call Main - On Delete.vi directly" so that it isn't forgotten.

**Comment by debryant** [comment]
> Update the palette file to be titled Scan Engine

The top level palette for an API is regularly called "dir.mnu". Subpalettes have meaningful names. This is following the pattern set in the R&D and SLSC Switch palettes as well. Do you still prefer I change this file's name?
image

**Comment by debryant** [comment]
Just realized maybe you are referring to its title in the palette itself? But here it already reads "Scan Engine"
image

**Comment by debryant** [comment]
Just realized maybe you were referring to the palette name shown in the palette itself, but here it reads Scan Engine....
image

**Comment by rtzoeller** [comment]
I was referring to the one in LabVIEW, not the on-disk name, correct.

I just removed the installed directory, cleared the local Built folder, and did a rebuild of the API then re-launched LabVIEW.

I am still seeing "Routing and Faulting", so it seems like the file is not up-to-date in the git repo compared to the version in your local vi.lib.

image
image
palette

**Review by rtzoeller — APPROVED** [review]

**Comment by debryant** [comment]
This PR successfully built w/o my needing to re-merge the project file by hand. With Ryan's approval, can it be merged now, or does it need Donovan to review it 1st?

**Comment by debryant** [comment]
Ah... already done. Thanks!

**Comment by rtzoeller** [comment]
No problem, was just waiting on a successful build (since you added a build spec that would interact with @Sarci1's changes).

**Comment by rtzoeller** [comment]
Oh, except we weren't running that build spec on the build machines. So I didn't need to wait. Whoops!

**Pull request merged**
