### PR TITLE
Add Test to Ensure Modules Properties Are Not Lost When Being used to Create New Modules

### PR DESCRIPTION
**Pull request by oscarfonloz**
# :warning: [PR 143](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/pull/143) must be merged first into main.

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

1. Added a new test to ensure we do not lose module's properties when setting and getting their data across multiple slots
2. Fixed the style of a couple of existing tests to make them more readable

### Why should this Pull Request be merged?

Expands our test suite and ensures we do not break functionality as we keep expanding the scripting API

### What testing has been done?

Ensured all tests run and added more

### CODE REVIEW

**Comment by rtzoeller** [comment]
Please update the PR title.

**Comment by oscarfonloz** [comment]
> Please update the PR title.

Thanks! Done 👍🏻

**Comment by rtzoeller** [comment]
We seem to be using two different patterns for calling `Get Slot.vim`.

In the new test, we are passing a new class constant to specify the type:
image

In some of the existing tests, we pass the existing class wire:
image

I have a slight preference for the first approach, as the second approach will pass if `Get Slot.vim` just returns the input. Can you update _just the tests which are already modified by this PR_ to use this approach throughout?

---

Why is `Allow Polymorphic VI to Adapt to Data Type` being re-enabled for `Create Counter Driven Output Module.vi`?

**Comment by oscarfonloz** [comment]
> We seem to be using two different patterns for calling `Get Slot.vim`.
> 
> In the new test, we are passing a new class constant to specify the type
> In some of the existing tests, we pass the existing class wire
> 
> I have a slight preference for the first approach, as the second approach will pass if `Get Slot.vim` just returns the input. Can you update _just the tests which are already modified by this PR_ to use this approach throughout?

I agree, I will change those in this PR and ensure they pass.

> Why is `Allow Polymorphic VI to Adapt to Data Type` being re-enabled for `Create Counter Driven Output Module.vi`?

Because I'm dumb and forgot to remove that VI, too 😂 Thank you!

**Review by rtzoeller — APPROVED** [review]

**Pull request merged**
