### PR TITLE
Add Tests for Add, Remove Custom Device and Add, Remove Local Chassis

### PR DESCRIPTION
**Pull request by Sarci1**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

**Custom Device Source/Tests/Unit Tests/Scripting API/Custom Device/test_Add Custom Device.vi** - Adds a custom device and verifies that the target properties change appropriately when sync to scan is selected.

**Custom Device Source/Tests/Unit Tests/Scripting API/Custom Device/test_Remove Custom Device.vi** - Adds a custom device, verifies it can be found, removes the custom devices, then verifies it cannot be found.

**Custom Device Source/Tests/Unit Tests/Scripting API/Custom Device/test_Add Local Chassis.vi** - Adds a custom device and local chassis, ensures the chassis has been added along with the appropriate number of slots.

**Custom Device Source/Tests/Unit Tests/Scripting API/Custom Device/test_Remove Local Chassis.vi** - Adds a custom device and local chassis, verifies the chassis can be found, removes the chassis, then verifies the chassis cannot be found.

**Scan Engine Scripting.lvlib/Find Scan Engine Custom Device.vi** - Addresses a bug where I was inappropriately closing a reference prematurely (found while executing previous mentioned tests).

### Why should this Pull Request be merged?

Provides unit tests for the current scripting API.

### What testing has been done?

Verified all the tests passed using the local JKI VI Tester tool.

### CODE REVIEW

**Comment by rtzoeller** [comment]
I haven't had a chance to look at the rest of the changes closely, but I'd prefer if we cleaned up the reference closing a bit more. In particular:

image

- [ ] There's no need to close the result of `FindChildrenByGUID` both inside and outside the case structure -- we can remove the close call circled in red.
- [ ] I'd prefer if we branched the result of `GetCustomDevices` going in to the loop and passed it to close outside of the loop, rather than passing it through the loop (highlighted). Passing it through the loop makes it look like the reference could change, when it can't.

**Comment by Sarci1** [comment]
@rtzoeller 
* [x]  There's no need to close the result of `FindChildrenByGUID` both inside and outside the case structure -- we can remove the close call circled in red.
* [x]  I'd prefer if we branched the result of `GetCustomDevices` going in to the loop and passed it to close outside of the loop, rather than passing it through the loop (highlighted). Passing it through the loop makes it look like the reference could change, when it can't.

**Comment by rtzoeller** [comment]
- [ ] It seems like all of the tests use the same setup logic. 
image

Move that to the `setUp.vi` provided by the test class (the references can be bundled in the class data, and unbundled in the test), and close the references in `tearDown.vi`. I don't see these VIs in your test class (at least on GitHub), so you may need to copy them from another test class if they were deleted.

You'll need to run the tests through the interactive test runner to get `setUp` and `tearDown` to be called correctly. I'm guessing R+F has some examples of this shared setup/teardown logic.

**Comment by Sarci1** [comment]
> * [x]  It seems like all of the tests use the same setup logic.

Turns out I didn't target the right class either, so thank you for picking up on that.

**Review by rtzoeller — APPROVED** [review]

**Pull request merged**
