### PR TITLE
Dialogue added for NI-904x/NI-905x during auto-detect.

### PR DESCRIPTION
**Pull request by VincentRuault**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

We detect cRIO configuration, if "Slot Programming Mode" property is supported (NI-904x and NI-905x families), we display current slot property value and offer customer to change it.

### Why should this Pull Request be merged?

To address Issue #24 (enhancement)

### What testing has been done?

Manual testing on NI-9049 and a NI-9082 controllers.
For NI-9049, I had different modules, some not supporting Scan-Mode (a NI-9862 and a NI-9467 GPS module).

### CODE REVIEW

**Comment by rtzoeller** [comment]
I believe the build is failing due to a change made to that modules library that required changes to the custom device, which did not go in prior to these changes being made. Not really an issue; I was able to merge `ni:master` into the pull request locally and get a build going.

@VincentRuault can you merge the commits that have gone into this repository into your pull request so that the build succeeds? There are not any conflicts, so it should merge without an issue.

**Comment by rtzoeller** [comment]
- [ ] The UI for the dialog consists of separate controls. While we cannot put them in an array due to how we want to style them, we can at least create a typedef'd control of a cluster that represents a row, and use that cluster 8 times. You can use the `Controls[]` property on the cluster control to get references to the items in a cluster, which you can then use to disable/modify the enum inside the cluster.  (This change not reflected in the screenshot below).

- [ ] There are separate event structure cases for each "Slot Programming Mode" control. We can combine them into one, by searching the array of enum references you have built for the `CtlRef` value in the event structure to get the index to use for the slot number. Then just assign all of the value changed events to the same case.
image

- [ ] The modules are currently filling the dialog from the top. We should instead make the modules reflect their proper location in the chassis. For example, if there is only one module in the chassis, and it is in slot 6, it should appear in the 6th row in the dialog, not the first.

- [ ] Please update the the dialog title to "Change Slots Programming Mode".

- [ ] Confirm that we don't show any raw error messages from your code if either the target IP address is not formatted as an IP (e.g. put a period at the end) or the target does not exist/is offline. Right now errors from nisyscfg are being shown directly, coming from your code.
image
If this is the same as the existing behavior for auto-detect in this condition, I am less concerned about fixing it.

- [ ] The VI names have underscores in them. It looks like the rest of the custom device just uses spaces, so yours should too. The existing code is not terribly consistent here, so this is minor.

**Comment by VincentRuault** [comment]
Hi @rtzoeller ,
I just committed:
https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/pull/31/commits/24d7c5a0b4021fb5db72bbcc8e983e21dad9f93c

Here is what I addressed (I didn't address the last one (minor), in your request):
> * [ x]  The UI for the dialog consists of separate controls. While we cannot put them in an array due to how we want to style them, we can at least create a typedef'd control of a cluster that represents a row, and use that cluster 8 times. You can use the `Controls[]` property on the cluster control to get references to the items in a cluster, which you can then use to disable/modify the enum inside the cluster.  (This change not reflected in the screenshot below).
> * [ x]  There are separate event structure cases for each "Slot Programming Mode" control. We can combine them into one, by searching the array of enum references you have built for the `CtlRef` value in the event structure to get the index to use for the slot number. Then just assign all of the value changed events to the same case.
>   image
> * [x ]  The modules are currently filling the dialog from the top. We should instead make the modules reflect their proper location in the chassis. For example, if there is only one module in the chassis, and it is in slot 6, it should appear in the 6th row in the dialog, not the first.
> * [ x]  Please update the the dialog title to "Change Slots Programming Mode".

Regards

**Comment by rtzoeller** [comment]
- [ ] It looks like `Set FPGA Mode.vi` and `Get Target IP Address.vi` were unchanged. If this is the case, please revert them.

**Comment by rtzoeller** [comment]
@VincentRuault it looks like rewriting the commits to not touch the files I mentioned earlier somehow detached it from this pull request. E.g. I still see four commits when looking at GitHub, and none of them are that one. It might be easiest to create a new pull request to fix this.

Other feedback:
- [ ] Instead of prefixing the VIs with "Auto Detect_Programming Mode", make a folder and place them inside it. 
image

- [ ] Make sure the default states are all the same for the controls
image

- [ ] Change `Auto Detect_Programming Mode_Change property value.vi` to not update the module programming mode when "Don't Modify" is passed. Although we prevent this from happening in other parts of the code, we don't want to assume that.
image

- [ ] What is the motivation for the while loop here? Are you trying to avoid reading the strings from the module more than once?
image

**Comment by VincentRuault** [comment]
Hi @rtzoeller 

I'm closing this Pull Request and I just created a new one (#35), per your request. The #35 should address:
 [x]  Instead of prefixing the VIs with "Auto Detect_Programming Mode", make a folder and place them inside it.
>   image
> * [X]  Make sure the default states are all the same for the controls
>   image
> * [X]  Change `Auto Detect_Programming Mode_Change property value.vi` to not update the module programming mode when "Don't Modify" is passed. Although we prevent this from happening in other parts of the code, we don't want to assume that.
>   image
> * [X]  What is the motivation for the while loop here? Are you trying to avoid reading the strings from the module more than once?
>   image
**YES, it's reason why**

**Pull request closed without merging**
