### PR TITLE
Add existing create and read methods to polymorphic VIs

### PR DESCRIPTION
**Pull request by oscarfonloz**
## ℹ️ This PR branches from NI\main

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This PR adds the missing polymorphic VIs for the Read and Create functions for the modules we have added lately.

### Why should this Pull Request be merged?

It completes the existing modules in the repo

### What testing has been done?

All unit tests pass. I also visually inspected each instance to ensure the same settings are used for all of them

### CODE REVIEW

**Comment by rtzoeller** [comment]
- [ ] Palettes need to be updated to have the new VIs. If no other PRs are currently modifying the palettes, I'd prefer that this PR include that change as it makes reviewing easier. Otherwise, this can be deferred.
- [ ] My initial reaction is that "Allow Polymorphic VI to Adapt to Data Type" should be off for the "Create" poly-VIs (a change), and on for the "Read" poly-VIs (what you've implemented). Module creation should be explicit, and having the module type change depending on what's wired is surprising to me, especially since many of the modules share signatures. @buckd thoughts?

**Comment by oscarfonloz** [comment]
> * [ ]  Palettes need to be updated to have the new VIs. If no other PRs are currently modifying the palettes, I'd prefer that this PR include that change as it makes reviewing easier. Otherwise, this can be deferred.

@debryant is working on the palettes. I am fine if we prefer to abandon this PR, and [PR 143](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/pull/143), and ask Deborah to submit all at the same time. She is already working in the branch that has the documentation, which has all of these changes merged.

What do y'all prefer? We can bring this up in the Teams chat.

> * [ ]  My initial reaction is that "Allow Polymorphic VI to Adapt to Data Type" should be off for the "Create" poly-VIs (a change), and on for the "Read" poly-VIs (what you've implemented). Module creation should be explicit, and having the module type change depending on what's wired is surprising to me, especially since many of the modules share signatures. @buckd thoughts?

Makes sense to me. I am down to making these changes.

**Comment by rtzoeller** [comment]
I'll end up taking another look at the VIs once the "Adapt to Type" change is made, so I'm fine if this gets closed and submitted as part of a separate PR. Whatever is easiest for you.

**Comment by rtzoeller** [comment]
`Create Counter Driven Output Module.vi` and `Read Counter Driven Output Module.vi` are reporting no changes. If that's expected, please revert them.

**Comment by oscarfonloz** [comment]
> `Create Counter Driven Output Module.vi` and `Read Counter Driven Output Module.vi` are reporting no changes. If that's expected, please revert them.

Removed :)

**Review by rtzoeller — APPROVED** [review]

**Pull request merged**
