### PR TITLE
Adding Support for 9216 (RTD) module

### PR DESCRIPTION
**Pull request by dbendele**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds support for 9216 module in module models enum.

### Why should this Pull Request be merged?

required for pull request: https://github.com/ni/niveristand-scan-engine-module-libraries/pull/28

### What testing has been done?

Unit tests passed locally.
same testing as linked pull request:
SEECD deploys with VS 2017 (with the 9216 module added to system definition) correctly
The 9216 settings were changed to exercise all options of device-specific config.
Deploy and test successful to Linux64 target (9045).

### CODE REVIEW

**Comment by rtzoeller** [comment]
This build is expected to fail. I will work with @dbendele to get a build before submitting this (likely after the code has been reviewed and any feedback is addressed).

**Comment by rtzoeller** [comment]
## Main - On Load.vi

- [ ] Your new mutation case appears to be based off of case # 4, which added support for the 9214. This is actually more complicated than it needs to be; you can use the beginning logic from case # 5,6 to do the same thing.

image


The reason that the 9214 case needed to be handled differently than yours was that the 9214 was previously represented in shipping code as a different class, and needed to be explicitly converted. Since you are introducing a new module, this doesn't apply and the standard "fix how LabVIEW broke my enums" conversion needs to be run.

It does look like all of the mutation here is a bit wonky, since we end up running some mutation we ought to run once multiple times (although to no detriment). I might file a bug on that.

**Comment by dbendele** [comment]
https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/pull/77/commits/7afc6e0b9c85b461cd988b9c0b8a920b37caa60a
resolves Ryan's review feedback.

**Comment by dbendele** [comment]
build of this commit was aborted because it did not correctly reference the export from the related/dependent [pull request](https://github.com/ni/niveristand-scan-engine-module-libraries/pull/28) for the updated modules component.

**Comment by dbendele** [comment]
Thanks for guiding the effort towards my first commit to this repo.

**Pull request merged**
