### PR TITLE
Add DI mode class

### PR DESCRIPTION
**Pull request by rdecarreau**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Add the Digital Input Mode to the set of modes for modules. This will be used by the forthcoming 9422 module scripting.

### Why should this Pull Request be merged?

The 9422 needs digital input mode.

### What testing has been done?

Ran the VI Test locally.

### CODE REVIEW

**Comment by rtzoeller** [comment]
- [ ] The `Create *** Module.vi` implementations all do different things with regards to error chaining - we should be consistent. `Create Digital Input Module.vi` should chain the error through the `To More Specific Class`, as should `Create Digital Output Module.vi`. `Create PWM Output Module.vi` should chain the error through `Read Mode.vi`.

- [ ] The existing mode classes use different icon banner colors, which helps in telling them apart. I'd prefer to choose a different color than the existing `Digital Output Mode` class. It seems like `Digital Output Mode` should have been yellow, since `DO Channel` is yellow. I

f it won't cause issues for the rest of your team, I'd prefer if these changes were included in this PR. If it's unclear if they will cause issues, let me know.

**Comment by rdecarreau** [comment]
Updated various Create vi's to chain errors through all things through which errors can be chained.

Going back and changing all of the colors would probably not be a great thing to spur a million vi changes at this point. I did change the DO to yellow, though, because they are so similar to each other already we need more differentiation.

**Comment by debryant** [comment]
I agree with Robert on the colors at this point. I'd like to take a "clean-up" pass when just about done and address things like banner colors, window positioning/sizing, adjust control layout, label consistency, etc. These kinds of things are easier to see when flying out and looking at the whole picture. I've created AzDO task 1176064 (https://ni.visualstudio.com/DevCentral/_workitems/edit/1176064) for this to address near the end.

**Review by rtzoeller — APPROVED** [review]

**Comment by debryant** [comment]
Does @buckd have the gate on this?

**Comment by niphilj** [comment]
> Does @buckd have the gate on this?

I believe @niphilj does and I'm looking at it now.

**Review by niphilj — APPROVED** [review]
Thanks for thinking through Ryan's comments. The changes seemed fairly straight forward. 

The one comment related to style, and only because I was trying to follow the logic since being picky wasn't my goal, is related to the wiring and how some wires overlap making it difficult to assert exactly which terminals are connected. Particularly here in all 4 VIs:
image
And this is one case, that I would have opted to have a little more whitespace between nodes for readability - maybe for future reference. I do like the error wire being consistent as Ryan asked, this was just a strange side-effect.

**Comment by debryant** [comment]
Good comment @niphilj. I added this to the "final scrub" task item that I mentioned above, so if it isn't addressed before then....

**Pull request merged**
