### PR TITLE
Fix module terminal positions in Scripting API

### PR DESCRIPTION
**Pull request by oscarfonloz**
# ⚠️ [PR 153](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/pull/153) must go in first

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Homogenizes the terminals assignment of all modules.

### Why should this Pull Request be merged?

Because we currently have module creation nodes that do not have the channel setting in the first input of their VIs

### What testing has been done?

Ran and fixed all unit tests. Ran and fixed all examples.

### CODE REVIEW

**Comment by oscarfonloz** [comment]
I believe Get Slot.vim changes because it consumes from a VI that changed (the 9212 and 9213 converters). Let me know if this is not the case and we can remove it from the PR.

**Comment by rtzoeller** [comment]
- [ ] Some of the test VIs also take in the same parameters, but are now flipped from the non-test VIs. For example, `NI 9475 Test.lvclass:Create and Read CDO.vi` still has `drive from slot in` above `channel settings in`.
- [ ] We should update the control and indicator positions on the front panels to match the order on the connector pane.

**Comment by oscarfonloz** [comment]
> * [x]  Some of the test VIs also take in the same parameters, but are now flipped from the non-test VIs. For example, `NI 9475 Test.lvclass:Create and Read CDO.vi` still has `drive from slot in` above `channel settings in`.
> * [x]  We should update the control and indicator positions on the front panels to match the order on the connector pane.

Thanks for the comments. I have addressed both. Let me know if I missed any :)

**Comment by rtzoeller** [comment]
@oscarfonloz the following VIs' front panels still need to be updated (also check block diagram):

- `Read NI 9474 - Counter Driven Output.vi`
- `Read NI 9475 - Counter Driven Output.vi`

**Review by rtzoeller — APPROVED** [review]

**Pull request merged**
