### PR TITLE
Updated Get Slot to malleable

### PR DESCRIPTION
**Pull request by rdecarreau**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Update the Get Slot vi to malleable

### Why should this Pull Request be merged?

Users will no longer have to cast the class output to the desired module. 

### What testing has been done?

Updated all test VIs with malleable vi and reran tests.

### CODE REVIEW

**Comment by rtzoeller** [comment]
Overall, I like the change quite a bit. I did have to manually force a recompile on several VIs, which was a bit unusual.

@buckd any compatibility concerns with a malleable VI being directly part of the public API?

---

IMO, the `module in` input should probably be recommended, not required. The existing usage is predicated on knowing the module type ahead of time, but that isn't the only possible use of the API. If we make the input recommended and leave the default value as the Module class, we'll always return the slot configuration, and things like the module name and number of channels can be generically queried.

---

Whenever malleables come into play, I find myself asking "What if I pass in something stupid?" For example, what happens if I pass in a class which isn't derived from `Module.lvclass` at all?

In the current implementation, we get a bit lucky - `Get Slot.vim` happens to call VIs which expect a `Module.lvclass` instance like `Convert to CI PWM Module.vi`, resulting in the calling VI breaking. But frankly there's no reason those VIs couldn't also become VIMs in the future, just like `Get Slot.vim`. 

Since this is part of the public API, it'd be nice to defensively force other types to be compile-time errors, rather than runtime errors, even if we happen to change the internal implementation down the road. This also lets us document exactly what types we expect to be passed.

LabVIEW 2017 lacks `Assert Same or Descendant Type.vim`, which is present in 2020 and possibly earlier, but fortunately that is not a builtin and we can borrow from its implementation. It turns out a call to `To More Generic Class` does quite nicely.

image

Here's what using "Convert Instance VI to Standard VI" looks like when I pass an unrelated class:


Please make this change in your implementation.

**Comment by rdecarreau** [comment]
>the module in input should probably be recommended, not required

I agree, I like that operating model a lot!

> Since this is part of the public API, it'd be nice to defensively force other types to be compile-time error

I agree, @oscarfonloz and I talked about this right before I PR'd. I like your solution that is quite eloquent and concise. I was trying to think of how to "break" it at compile time instead of runtime. Thanks!

**Comment by buckd** [comment]
> any compatibility concerns with a malleable VI being directly part of the public API?

I think it's fine to have a malleable as part of the API. I think this will work in LabVIEW 2017. I don't think the changes for classes with malleables in 2017 SP1 are necessary, but it might be a good idea to try at some point. We can still use the malleable if it doesn't work in non-SP1 versions, but we should document it.

**Comment by rtzoeller** [comment]
Changes look good, just a few small requests before I merge this:

- Please update the palettes to point to the VIM? I believe they are still pointing to the old `Get Slot.vi`.
- Please add a test that _doesn't_ wire a module type as an input, to validate that a generic module is returned which can then be casted.

**Comment by rdecarreau** [comment]
Ready to review new test and pallete

**Comment by rtzoeller** [comment]
@rdecarreau the palette file seems to be improperly linked; it is pointing at `vi.lib\addons\VeriStand Custom Device Scripting APIs\Slots\Get Slot.vim`, when it should be pointing at `vi.lib\addons\VeriStand Custom Device Scripting APIs\Scan Engine\Slots\Get Slot.vim`. This is causing it to appear broken for me.

**Review by rtzoeller — APPROVED** [review]
The test looks good, so this is just waiting on the palette fix.

**Pull request merged**
