### PR TITLE
Dialogue added for NI-904x/NI-905x during auto-detect (cont.).

### PR DESCRIPTION
**Pull request by VincentRuault**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This is continuation of Pull Request #31. 
We detect cRIO configuration, if "Slot Programming Mode" property is supported (NI-904x and NI-905x families), we display current slot property value and offer customer to change it.

### Why should this Pull Request be merged?

To address Issue #24 (enhancement)

### What testing has been done?

Manual testing on NI-9049 and a NI-9082 controllers.
For NI-9049, I had different modules, some not supporting Scan-Mode (a NI-9862 and a NI-9467 GPS module).

### CODE REVIEW

**Comment by csjall** [comment]
The PR is failing due to some missing (Auto Detect *) files. It seems you removed some files from the project but failed to update the lvlib before committing.

**Comment by VincentRuault** [comment]
Hi @csjall , did my latest commit allow to not fail anymore?
Regards

**Comment by csjall** [comment]
- [ ] In `Main - Auto Detect Modules.vi':
image

**Comment by VincentRuault** [comment]
Commit def3b96: changes applied:
> * [x]  In Main - Auto Detect Modules.vi:
>   There is a broken reference to
>   image
> * [x]  Rename "Change property value" to something more descriptive. I recommend "Set Slot Programming Mode". Be sure to capitalize letters.
> * [x]  Remove "LabVIEW FPGA" case in the top level switch. "Don't modify" and "Default" should be sufficient.
>   image
> * [x]  Add unique handler for "Default" case in the inner switch. We should probably error/warn if there is some unknown slot programming mode in the future.
> * [x]  In Initialize UI Elements: Remove 8 constant. Use auto-indexing for the reference array.
>   image
> * [x]  We have two typedefs that are similarly named. Consider renaming one to disambiguate. One is the Slot Programming Mode. The other is a UI cluster for configuring the slot. Consider renaming to Slot - Configuration.ctl.
>   image

**Comment by csjall** [comment]
- [ ] Read Property.vi is broken.
image

- [ ] You created a separate case for "Default", but it still has the same implementation as "Scan Engine". My intention was to do something different in the default case. Either return an error or set module programming mode to "None".

image

**Comment by VincentRuault** [comment]
"Read Property" was not part of previous commit but it broke because we had renamed a Typedef used.
For "Set Slot Programming Mode.vi": icone updated to reflect new name and also, inner case "Default" now set the Slot Programming Mode to "None".

> * [x]  Read Property.vi is broken.
> 
> image
> 
> * [x]  Update icon for Set Slop Programming mode.
> 
> image
> 
> * [x]  You created a separate case for "Default", but it still has the same implementation as "Scan Engine". My intention was to do something different in the default case. Either return an error or set module programming mode to "None".
> 
> image

**Comment by csjall** [comment]
The implementation looks good. I just have a nit picky UI detail.

- [ ] Align the text with the check box.
image

**Comment by VincentRuault** [comment]
Change applied. 
> The implementation looks good. I just have a nit picky UI detail.
> 
> * [x]  Align the text with the check box.
>   image

**Pull request merged**
